# models.py
from django.db import models
from django.contrib.auth.models import User

class FormProject(models.Model):
    nombre_dependencia = models.CharField(max_length=255, null=True, blank=True, default="")
    area_adscripcion = models.CharField(max_length=255, null=True, blank=True, default="")
    nombre_registrante = models.CharField(max_length=255, null=True, blank=True, default="")
    apellido_paterno = models.CharField(max_length=255, null=True, blank=True, default="")
    apellido_materno = models.CharField(max_length=255, null=True, blank=True, default="")
    correo_institucional = models.EmailField(max_length=255, null=True, blank=True, default="")
    telefono_oficina = models.CharField(max_length=10, null=True, blank=True, default="")
    telefono_oficina_ext = models.CharField(max_length=10, null=True, blank=True, default="")
    correo_personal = models.EmailField(max_length=255, null=True, blank=True, default="")
    telefono_particular = models.CharField(max_length=10, null=True, blank=True, default="")

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='projects')
    project_id = models.CharField(max_length=50, unique=True, blank=True, null=True)
    fecha_registro = models.DateField(auto_now_add=True)
    project_name = models.CharField(max_length=255)
    sector = models.CharField(max_length=255)
    tipo_proyecto = models.CharField(max_length=255)
    tipo_entidad = models.CharField(max_length=255)
    dependencia = models.CharField(max_length=255, null=True, blank=True)
    organismo = models.CharField(max_length=255, null=True, blank=True)
    municipioEnd = models.CharField(max_length=255, null=True, blank=True)
    entidadEstado = models.CharField(max_length=255, null=True, blank=True)
    peticion_personal = models.CharField(max_length=255, null=True, blank=True)
    unidad_responsable = models.CharField(max_length=255)
    unidad_presupuestal = models.CharField(max_length=255)
    ramo_presupuestal = models.CharField(max_length=255)
    monto_federal = models.DecimalField(max_digits=1000, decimal_places=2, null=True, blank=True)
    monto_estatal = models.DecimalField(max_digits=1000, decimal_places=2, null=True, blank=True)
    monto_municipal = models.DecimalField(max_digits=1000, decimal_places=2, null=True, blank=True)
    monto_otros = models.DecimalField(max_digits=1000, decimal_places=2, null=True, blank=True)
    inversion_estimada = models.DecimalField(max_digits=1000, decimal_places=2, null=True, blank=True)
    descripcion = models.TextField()
    situacion_sin_proyecto = models.TextField()
    objetivos = models.TextField()
    metas = models.TextField()
    gasto_programable = models.CharField(max_length=255)
    programa_presupuestario = models.CharField(max_length=255)
    beneficiarios = models.IntegerField(null=True, blank=True)
    alineacion_normativa = models.TextField()
    region = models.CharField(max_length=255)
    municipio = models.CharField(max_length=255)
    municipio_impacto = models.JSONField(null=True, blank=True)
    localidad = models.CharField(max_length=255)
    barrio_colonia_ejido = models.CharField(max_length=255)
    latitud = models.FloatField()
    longitud = models.FloatField()
    plan_nacional = models.CharField(max_length=255)
    plan_estatal = models.CharField(max_length=255)
    plan_municipal = models.TextField(null=True, blank=True)
    ods = models.CharField(max_length=255)
    plan_sectorial = models.CharField(max_length=255)
    indicadores_estrategicos = models.CharField(max_length=255)
    indicadores_tacticos = models.CharField(max_length=255, null=True, blank=True)
    indicadores_desempeno = models.CharField(max_length=255, null=True, blank=True)
    indicadores_rentabilidad = models.CharField(max_length=255, null=True, blank=True)
    estado_inicial = models.ImageField(upload_to='documentos/estado_inicial/', null=True, blank=True)
    estado_con_proyecto = models.ImageField(upload_to='documentos/estado_con_proyecto/', null=True, blank=True)
    estudios_prospectivos = models.FileField(upload_to='documentos/estudios_prospectivos/', null=True, blank=True)
    estudios_factibilidad = models.FileField(upload_to='documentos/estudios_factibilidad/', null=True, blank=True)
    analisis_alternativas = models.FileField(upload_to='documentos/analisis_alternativas/', null=True, blank=True)
    validacion_normativa = models.FileField(upload_to='documentos/validacion_normativa/', null=True, blank=True)
    liberacion_derecho_via = models.FileField(upload_to='documentos/liberacion_derecho_via/', null=True, blank=True)
    situacion_sin_proyecto_fotografico = models.FileField(upload_to='documentos/situacion_sin_proyecto_fotografico/', null=True, blank=True)
    situacion_con_proyecto_proyeccion = models.FileField(upload_to='documentos/situacion_con_proyecto_proyeccion/', null=True, blank=True)
    analisis_costo_beneficio = models.FileField(upload_to='documentos/analisis_costo_beneficio/', null=True, blank=True)
    expediente_tecnico = models.FileField(upload_to='documentos/expediente_tecnico/', null=True, blank=True)
    proyecto_ejecutivo = models.FileField(upload_to='documentos/proyecto_ejecutivo/', null=True, blank=True)
    manifestacion_impacto_ambiental = models.FileField(upload_to='documentos/manifestacion_impacto_ambiental/', null=True, blank=True)
    otros_estudios = models.FileField(upload_to='documentos/otros_estudios/', null=True, blank=True)
    observaciones = models.TextField(null=True, blank=True)
    porcentaje_avance = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    estatus = models.CharField(max_length=50, choices=[('Atendido', 'Atendido'), ('En Proceso', 'En Proceso'), ('Registrado', 'Registrado')], default='Registrado')
    situacion = models.CharField(max_length=50, choices=[('Vigente', 'Vigente'), ('Antecedente', 'Antecedente'), ('Cancelado', 'Cancelado')], default='Vigente')
    retroalimentacion = models.TextField(null=True, blank=True)

    # Campos de bloqueo
    isBlocked_project = models.BooleanField(default=True)
    isBlocked_project_name = models.BooleanField(default=False)
    isBlocked_sector = models.BooleanField(default=False)
    isBlocked_tipo_proyecto = models.BooleanField(default=False)
    isBlocked_tipo_entidad = models.BooleanField(default=False)
    isBlocked_dependencia = models.BooleanField(default=False)
    isBlocked_organismo = models.BooleanField(default=False)
    isBlocked_municipioEnd = models.BooleanField(default=False)
    isBlocked_entidadEstado = models.BooleanField(default=False)
    isBlocked_peticion_personal = models.BooleanField(default=False)
    isBlocked_unidad_responsable = models.BooleanField(default=False)
    isBlocked_unidad_presupuestal = models.BooleanField(default=False)
    isBlocked_ramo_presupuestal = models.BooleanField(default=False)
    isBlocked_monto_federal = models.BooleanField(default=False)
    isBlocked_monto_estatal = models.BooleanField(default=False)
    isBlocked_monto_municipal = models.BooleanField(default=False)
    isBlocked_monto_otros = models.BooleanField(default=False)
    isBlocked_inversion_estimada = models.BooleanField(default=False)
    isBlocked_descripcion = models.BooleanField(default=False)
    isBlocked_situacion_sin_proyecto = models.BooleanField(default=False)
    isBlocked_objetivos = models.BooleanField(default=False)
    isBlocked_metas = models.BooleanField(default=False)
    isBlocked_gasto_programable = models.BooleanField(default=False)
    isBlocked_programa_presupuestario = models.BooleanField(default=False)
    isBlocked_beneficiarios = models.BooleanField(default=False)
    isBlocked_alineacion_normativa = models.BooleanField(default=False)
    isBlocked_region = models.BooleanField(default=False)
    isBlocked_municipio = models.BooleanField(default=False)
    isBlocked_municipio_impacto = models.BooleanField(default=False)
    isBlocked_localidad = models.BooleanField(default=False)
    isBlocked_barrio_colonia_ejido = models.BooleanField(default=False)
    isBlocked_latitud = models.BooleanField(default=False)
    isBlocked_longitud = models.BooleanField(default=False)
    isBlocked_plan_nacional = models.BooleanField(default=False)
    isBlocked_plan_estatal = models.BooleanField(default=False)
    isBlocked_plan_municipal = models.BooleanField(default=False)
    isBlocked_ods = models.BooleanField(default=False)
    isBlocked_plan_sectorial = models.BooleanField(default=False)
    isBlocked_indicadores_estrategicos = models.BooleanField(default=False)
    isBlocked_indicadores_tacticos = models.BooleanField(default=False)
    isBlocked_indicadores_desempeno = models.BooleanField(default=False)
    isBlocked_indicadores_rentabilidad = models.BooleanField(default=False)
    isBlocked_estado_inicial = models.BooleanField(default=False)
    isBlocked_estado_con_proyecto = models.BooleanField(default=False)
    isBlocked_estudios_prospectivos = models.BooleanField(default=False)
    isBlocked_estudios_factibilidad = models.BooleanField(default=False)
    isBlocked_analisis_alternativas = models.BooleanField(default=False)
    isBlocked_validacion_normativa = models.BooleanField(default=False)
    isBlocked_liberacion_derecho_via = models.BooleanField(default=False)
    isBlocked_situacion_sin_proyecto_fotografico = models.BooleanField(default=False)
    isBlocked_situacion_con_proyecto_proyeccion = models.BooleanField(default=False)
    isBlocked_analisis_costo_beneficio = models.BooleanField(default=False)
    isBlocked_expediente_tecnico = models.BooleanField(default=False)
    isBlocked_proyecto_ejecutivo = models.BooleanField(default=False)
    isBlocked_manifestacion_impacto_ambiental = models.BooleanField(default=False)
    isBlocked_otros_estudios = models.BooleanField(default=False)
    isBlocked_observaciones = models.BooleanField(default=False)
    isBlocked_porcentaje_avance = models.BooleanField(default=False)
    isBlocked_estatus = models.BooleanField(default=False)
    isBlocked_situacion = models.BooleanField(default=False)
    isBlocked_retroalimentacion = models.BooleanField(default=False)

    # Campos de observación
    observacion_project_name = models.TextField(null=True, blank=True)
    observacion_sector = models.TextField(null=True, blank=True)
    observacion_tipo_proyecto = models.TextField(null=True, blank=True)
    observacion_tipo_entidad = models.TextField(null=True, blank=True)
    observacion_dependencia = models.TextField(null=True, blank=True)
    observacion_organismo = models.TextField(null=True, blank=True)
    observacion_municipioEnd = models.TextField(null=True, blank=True)
    observacion_entidadEstado = models.TextField(null=True, blank=True)
    observacion_peticion_personal = models.TextField(null=True, blank=True)
    observacion_unidad_responsable = models.TextField(null=True, blank=True)
    observacion_unidad_presupuestal = models.TextField(null=True, blank=True)
    observacion_ramo_presupuestal = models.TextField(null=True, blank=True)
    observacion_monto_federal = models.TextField(null=True, blank=True)
    observacion_monto_estatal = models.TextField(null=True, blank=True)
    observacion_monto_municipal = models.TextField(null=True, blank=True)
    observacion_monto_otros = models.TextField(null=True, blank=True)
    observacion_inversion_estimada = models.TextField(null=True, blank=True)
    observacion_descripcion = models.TextField(null=True, blank=True)
    observacion_situacion_sin_proyecto = models.TextField(null=True, blank=True)
    observacion_objetivos = models.TextField(null=True, blank=True)
    observacion_metas = models.TextField(null=True, blank=True)
    observacion_gasto_programable = models.TextField(null=True, blank=True)
    observacion_programa_presupuestario = models.TextField(null=True, blank=True)
    observacion_beneficiarios = models.TextField(null=True, blank=True)
    observacion_alineacion_normativa = models.TextField(null=True, blank=True)
    observacion_region = models.TextField(null=True, blank=True)
    observacion_municipio = models.TextField(null=True, blank=True)
    observacion_municipio_impacto = models.TextField(null=True, blank=True)
    observacion_localidad = models.TextField(null=True, blank=True)
    observacion_barrio_colonia_ejido = models.TextField(null=True, blank=True)
    observacion_latitud = models.TextField(null=True, blank=True)
    observacion_longitud = models.TextField(null=True, blank=True)
    observacion_plan_nacional = models.TextField(null=True, blank=True)
    observacion_plan_estatal = models.TextField(null=True, blank=True)
    observacion_plan_municipal = models.TextField(null=True, blank=True)
    observacion_ods = models.TextField(null=True, blank=True)
    observacion_plan_sectorial = models.TextField(null=True, blank=True)
    observacion_indicadores_estrategicos = models.TextField(null=True, blank=True)
    observacion_indicadores_tacticos = models.TextField(null=True, blank=True)
    observacion_indicadores_desempeno = models.TextField(null=True, blank=True)
    observacion_indicadores_rentabilidad = models.TextField(null=True, blank=True)
    observacion_estado_inicial = models.TextField(null=True, blank=True)
    observacion_estado_con_proyecto = models.TextField(null=True, blank=True)
    observacion_estudios_prospectivos = models.TextField(null=True, blank=True)
    observacion_estudios_factibilidad = models.TextField(null=True, blank=True)
    observacion_analisis_alternativas = models.TextField(null=True, blank=True)
    observacion_validacion_normativa = models.TextField(null=True, blank=True)
    observacion_liberacion_derecho_via = models.TextField(null=True, blank=True)
    observacion_situacion_sin_proyecto_fotografico = models.TextField(null=True, blank=True)
    observacion_situacion_con_proyecto_proyeccion = models.TextField(null=True, blank=True)
    observacion_analisis_costo_beneficio = models.TextField(null=True, blank=True)
    observacion_expediente_tecnico = models.TextField(null=True, blank=True)
    observacion_proyecto_ejecutivo = models.TextField(null=True, blank=True)
    observacion_manifestacion_impacto_ambiental = models.TextField(null=True, blank=True)
    observacion_otros_estudios = models.TextField(null=True, blank=True)
    observacion_observaciones = models.TextField(null=True, blank=True)
    observacion_porcentaje_avance = models.TextField(null=True, blank=True)
    observacion_estatus = models.TextField(null=True, blank=True)
    observacion_situacion = models.TextField(null=True, blank=True)
    observacion_retroalimentacion = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.project_name
