# utils.py

siglas = {
    'Dependencia': {
        'Secretaría del Despacho del Gobernador': 'SDG',
        'Oficialía Mayor': 'OFM',
        'Unidad de Planeación y Prospectiva': 'UPL',
        'Secretaría de Gobierno': 'GOB',
        'Secretaría de Hacienda': 'HAC',
        'Secretaría de Bienestar e Inclusión Social': 'SBI',
        'Secretaría de Infraestructura Pública y Desarrollo Urbano Sostenible': 'SIP',
        'Secretaría de Desarrollo Económico': 'SDE',
        'Secretaría de Medio Ambiente y Recursos Naturales': 'SMR',
        'Secretaría de Agricultura y Desarrollo Rural': 'SAD',
        'Secretaría de Turismo': 'TUR',
        'Secretaría de Contraloría': 'CON',
        'Secretaría de Educación Pública': 'SEP',
        'Secretaría de Salud': 'SLD',
        'Secretaría de Seguridad Pública': 'SEG',
        'Secretaría del Trabajo y Previsión Social': 'STP',
        'Secretaría de Movilidad y Transporte': 'SMT',
        'Secretaría de Cultura': 'CUL',
        'Procuraduría General de Justicia': 'PGJ',
        # Add all other dependencies here...
    },
    'Organismo': {
        'Centro de Justicia para Mujeres del Estado de Hidalgo': 'CJM',
        'Ciudad de las Mujeres': 'CMU',
        'Instituto Hidalguense de las Mujeres': 'IMU',
        'Instituto Hidalguense para el Desarrollo Municipal': 'IND',
        'Instituto Catastral del Estado de Hidalgo': 'ICA',
        'Instituto para Devolver al Pueblo lo Robado': 'IPR',
        'Centro Estatal de Maquinaria para el Desarrollo': 'CMD',
        'Comisión de Agua y Alcantarillado del Sistema Valle del Mezquital': 'CAV',
        'Comisión de Agua y Alcantarillado de Sistemas Intermunicipales': 'CAI',
        'Comisión Estatal del Agua y Alcantarillado': 'CEA',
        'Comisión Estatal de Vivienda': 'CEV',
        'Policía Industrial Bancaria del Estado de Hidalgo': 'PIB',
        'Consejo Estatal para la Cultura y las Artes de Hidalgo': 'CCA',
        'Escuela de Música del Estado de Hidalgo': 'EMH',
        'Servicios de Salud de Hidalgo': 'SSH',
        'Agencia de Desarrollo Valle de Plata': 'AVP',
        'Agencia Estatal de Energía': 'AEE',
        'Corporación de Fomento de Infraestructura Industrial': 'FII',
        'Corporación Internacional Hidalgo': 'CIH',
        'Instituto Hidalguense de Competitividad Empresarial': 'IHC',
        'Comisión Estatal de Biodiversidad de Hidalgo': 'COE',
        'Centro de Conciliación Laboral del Estado de Hidalgo': 'CLH',
        'Instituto de Capacitación para el Trabajo del Estado de Hidalgo': 'CTH',
        'Operadora de Eventos del Estado de Hidalgo': 'OEH',
        'Bachillerato del Estado de Hidalgo': 'BEH',
        'Colegio de Bachilleres del Estado de Hidalgo': 'CBH',
        'Colegio de Educación Profesional Técnica del Estado de Hidalgo': 'EPT',
        'Colegio de Estudios Científicos y Tecnológicos del Estado de Hidalgo': 'ECT',
        'El Colegio del Estado de Hidalgo': 'CEH',
        'Instituto Hidalguense de Educación': 'IHE',
        'Instituto Hidalguense de Educación para Adultos': 'IHA',
        'Instituto Hidalguense de Financiamiento a la Educación Superior': 'IHF',
        'Instituto Hidalguense de la Infraestructura Física Educativa': 'IFE',
        'Instituto Hidalguense del Deporte': 'IHD',
        'Instituto Tecnológico Superior de Huichapan': 'ITH',
        'Instituto Tecnológico Superior del Occidente del Estado de Hidalgo': 'ITS',
        'Instituto Tecnológico Superior del Oriente del Estado de Hidalgo': 'ITE',
        'Radio y Televisión de Hidalgo': 'RTH',
        'Universidad Intercultural del Estado de Hidalgo': 'UIC',
        'Universidad Politécnica de Francisco I. Madero': 'UPF',
        'Universidad Politécnica de Huejutla': 'UPH',
        'Universidad Politécnica de la Energía': 'UPE',
        'Universidad Politécnica de Pachuca': 'UPP',
        'Universidad Politécnica de Tulancingo': 'UPT',
        'Universidad Politécnica Metropolitana de Hidalgo': 'UPM',
        'Universidad Tecnológica de la Huasteca Hidalguense': 'UTH',
        'Universidad Tecnológica de la Sierra Hidalguense': 'UTS',
        'Universidad Tecnológica de la Zona Metropolitana del Valle de México': 'UTV',
        'Universidad Tecnológica de Mineral de la Reforma': 'UTM',
        'Universidad Tecnológica de Tulancingo': 'UTT',
        'Universidad Tecnológica de Tula-Tepeji': 'UTU',
        'Universidad Tecnológica del Valle del Mezquital': 'UVM',
        'Universidad Tecnológica Minera de Zimapán': 'UTZ',
        'Instituto Hidalguense de la Juventud': 'IHJ',
        'Instituto para la Atención de las y los Adultos Mayores del Estado de Hidalgo': 'IAA',
        'Sistema de Convencional': 'STC',
        'Sistema de Masivo': 'STM',
        'Comisión Estatal Para el Desarrollo Sostenible de los Pueblos Indígenas': 'CPI',
        'Consejo de Ciencia, Tecnología e Innovación de Hidalgo': 'CCT',
        'Consejo Rector de Pachuca Ciudad del Conocimiento y la Cultura': 'CCC',
        'Museo Interactivo para la Niñez y la Juventud "El Rehilete"': 'MIR',
        'Secretaría Técnica del Sistema Estatal Anticorrupción': 'SEA',
        'Distrito de Educación, Salud, Ciencia, Tecnología e Innovación': 'DSC',
        'Sistema para el Desarrollo Integral de las Familia del Estado de Hidalgo': 'DIF',
        'Universidad Digital del Estado de Hidalgo': 'UDH',
        # Add all other organisms here...
    },
    'Municipio': {
        '001 Acatlán': '001',
        '002 Acaxochitlán': '002',
        '003 Actopan': '003',
        '004 Agua Blanca de Iturbide': '004',
        '005 Ajacuba': '005',
        '006 Alfajayucan': '006',
        '007 Almoloya': '007',
        '008 Apan': '008',
        '009 El Arenal': '009',
        '010 Atitalaquia': '010',
        '011 Atlapexco': '011',
        '012 Atotonilco el Grande': '012',
        '013 Atotonilco de Tula': '013',
        '014 Calnali': '014',
        '015 Cardonal': '015',
        '016 Cuautepec de Hinojosa': '016',
        '017 Chapantongo': '017',
        '018 Chapulhuacán': '018',
        '019 Chilcuautla': '019',
        '020 Eloxochitlán': '020',
        '021 Emiliano Zapata': '021',
        '022 Epazoyucan': '022',
        '023 Francisco I. Madero': '023',
        '024 Huasca de Ocampo': '024',
        '025 Huautla': '025',
        '026 Huazalingo': '026',
        '027 Huehuetla': '027',
        '028 Huejutla de Reyes': '028',
        '029 Huichapan': '029',
        '030 Ixmiquilpan': '030',
        '031 Jacala de Ledezma': '031',
        '032 Jaltocán': '032',
        '033 Juárez Hidalgo': '033',
        '034 Lolotla': '034',
        '035 Metepec': '035',
        '036 San Agustín Metzquititlán': '036',
        '037 Metztitlán': '037',
        '038 Mineral del Chico': '038',
        '039 Mineral del Monte': '039',
        '040 La Misión': '040',
        '041 Mixquiahuala de Juárez': '041',
        '042 Molango de Escamilla': '042',
        '043 Nicolás Flores': '043',
        '044 Nopala de Villagrán': '044',
        '045 Omitlán de Juárez': '045',
        '046 San Felipe Orizatlán': '046',
        '047 Pacula': '047',
        '048 Pachuca de Soto': '048',
        '049 Pisaflores': '049',
        '050 Progreso de Obregón': '050',
        '051 Mineral de la Reforma': '051',
        '052 San Agustín Tlaxiaca': '052',
        '053 San Bartolo Tutotepec': '053',
        '054 San Salvador': '054',
        '055 Santiago de Anaya': '055',
        '056 Santiago Tulantepec de Lugo Guerrero': '056',
        '057 Singuilucan': '057',
        '058 Tasquillo': '058',
        '059 Tecozautla': '059',
        '060 Tenango de Doria': '060',
        '061 Tepeapulco': '061',
        '062 Tepehuacán de Guerrero': '062',
        '063 Tepeji del Río de Ocampo': '063',
        '064 Tepetitlán': '064',
        '065 Tetepango': '065',
        '066 Villa de Tezontepec': '066',
        '067 Tezontepec de Aldama': '067',
        '068 Tianguistengo': '068',
        '069 Tizayuca': '069',
        '070 Tlahuelilpan': '070',
        '071 Tlahuiltepa': '071',
        '072 Tlanalapa': '072',
        '073 Tlanchinol': '073',
        '074 Tlaxcoapan': '074',
        '075 Tolcayuca': '075',
        '076 Tula de Allende': '076',
        '077 Tulancingo de Bravo': '077',
        '078 Xochiatipan': '078',
        '079 Xochicoatlán': '079',
        '080 Yahualica': '080',
        '081 Zacualtipán de Ángeles': '081',
        '082 Zapotlán de Juárez': '082',
        '083 Zempoala': '083',
        '084 Zimapán': '084',
    }
}

sector_codes = {
    'Agua': '1a',
    'Comunicaciones y transportes': '1b',
    'Electricidad': '1c',
    'Hidrocarburos': '1d',
    'Turismo': '1e',
    'Educación': '2a',
    'Ciencia y tecnología': '2b',
    'Cultura': '2c',
    'Deportes': '2d',
    'Salud': '2e',
    'Seguridad social': '2f',
    'Urbanización y vivienda': '2g',
    'Asistencia social': '2h',
    'Seguridad nacional': '3a',
    'Seguridad pública': '3b',
    'Procuración de justicia': '3c',
    'Otros relacionados con el desarrollo económico y social': '3d',
    'Gubernamental, Oficinas administrativas': '4a',
    'No identificados en las clasificaciones anteriores': '5a',
}
