# utils.py

siglas = {
    'Dependencia': {
        'Secretaría del Despacho del Gobernador': 'SDG',
        'Oficialía Mayor': 'OFM',
        'Unidad de Planeación y Prospectiva': 'UPL',
        'Secretaría de Gobierno': 'GOB',
        'Secretaría de Hacienda': 'HAC',
        'Secretaría de Bienestar e Inclusión Social': 'SBI',
        'Secretaría de Infraestructura Pública y Desarrollo Urbano Sostenible': 'SIP',
        'Secretaría de Desarrollo Económico': 'SDE',
        'Secretaría de Medio Ambiente y Recursos Naturales': 'SMR',
        'Secretaría de Agricultura y Desarrollo Rural': 'SAD',
        'Secretaría de Turismo': 'TUR',
        'Secretaría de Contraloría': 'CON',
        'Secretaría de Educación Pública': 'SEP',
        'Secretaría de Salud': 'SLD',
        'Secretaría de Seguridad Pública': 'SEG',
        'Secretaría del Trabajo y Previsión Social': 'STP',
        'Secretaría de Movilidad y Transporte': 'SMT',
        'Secretaría de Cultura': 'CUL',
        'Procuraduría General de Justicia': 'PGJ',
        # Add all other dependencies here...
    },
    'Organismo': {
        'Centro de Justicia para Mujeres del Estado de Hidalgo': 'CJM',
        'Ciudad de las Mujeres': 'CMU',
        'Instituto Hidalguense de las Mujeres': 'IMU',
        'Instituto Hidalguense para el Desarrollo Municipal': 'IND',
        'Instituto Catastral del Estado de Hidalgo': 'ICA',
        'Instituto para Devolver al Pueblo lo Robado': 'IPR',
        'Centro Estatal de Maquinaria para el Desarrollo': 'CMD',
        'Comisión de Agua y Alcantarillado del Sistema Valle del Mezquital': 'CAV',
        'Comisión de Agua y Alcantarillado de Sistemas Intermunicipales': 'CAI',
        'Comisión Estatal del Agua y Alcantarillado': 'CEA',
        'Comisión Estatal de Vivienda': 'CEV',
        'Policía Industrial Bancaria del Estado de Hidalgo': 'PIB',
        'Consejo Estatal para la Cultura y las Artes de Hidalgo': 'CCA',
        'Escuela de Música del Estado de Hidalgo': 'EMH',
        'Servicios de Salud de Hidalgo': 'SSH',
        'Agencia de Desarrollo Valle de Plata': 'AVP',
        'Agencia Estatal de Energía': 'AEE',
        'Corporación de Fomento de Infraestructura Industrial': 'FII',
        'Corporación Internacional Hidalgo': 'CIH',
        'Instituto Hidalguense de Competitividad Empresarial': 'IHC',
        'Comisión Estatal de Biodiversidad de Hidalgo': 'COE',
        'Centro de Conciliación Laboral del Estado de Hidalgo': 'CLH',
        'Instituto de Capacitación para el Trabajo del Estado de Hidalgo': 'CTH',
        'Operadora de Eventos del Estado de Hidalgo': 'OEH',
        'Bachillerato del Estado de Hidalgo': 'BEH',
        'Colegio de Bachilleres del Estado de Hidalgo': 'CBH',
        'Colegio de Educación Profesional Técnica del Estado de Hidalgo': 'EPT',
        'Colegio de Estudios Científicos y Tecnológicos del Estado de Hidalgo': 'ECT',
        'El Colegio del Estado de Hidalgo': 'CEH',
        'Instituto Hidalguense de Educación': 'IHE',
        'Instituto Hidalguense de Educación para Adultos': 'IHA',
        'Instituto Hidalguense de Financiamiento a la Educación Superior': 'IHF',
        'Instituto Hidalguense de la Infraestructura Física Educativa': 'IFE',
        'Instituto Hidalguense del Deporte': 'IHD',
        'Instituto Tecnológico Superior de Huichapan': 'ITH',
        'Instituto Tecnológico Superior del Occidente del Estado de Hidalgo': 'ITS',
        'Instituto Tecnológico Superior del Oriente del Estado de Hidalgo': 'ITE',
        'Radio y Televisión de Hidalgo': 'RTH',
        'Universidad Intercultural del Estado de Hidalgo': 'UIC',
        'Universidad Politécnica de Francisco I. Madero': 'UPF',
        'Universidad Politécnica de Huejutla': 'UPH',
        'Universidad Politécnica de la Energía': 'UPE',
        'Universidad Politécnica de Pachuca': 'UPP',
        'Universidad Politécnica de Tulancingo': 'UPT',
        'Universidad Politécnica Metropolitana de Hidalgo': 'UPM',
        'Universidad Tecnológica de la Huasteca Hidalguense': 'UTH',
        'Universidad Tecnológica de la Sierra Hidalguense': 'UTS',
        'Universidad Tecnológica de la Zona Metropolitana del Valle de México': 'UTV',
        'Universidad Tecnológica de Mineral de la Reforma': 'UTM',
        'Universidad Tecnológica de Tulancingo': 'UTT',
        'Universidad Tecnológica de Tula-Tepeji': 'UTU',
        'Universidad Tecnológica del Valle del Mezquital': 'UVM',
        'Universidad Tecnológica Minera de Zimapán': 'UTZ',
        'Instituto Hidalguense de la Juventud': 'IHJ',
        'Instituto para la Atención de las y los Adultos Mayores del Estado de Hidalgo': 'IAA',
        'Sistema de Convencional': 'STC',
        'Sistema de Masivo': 'STM',
        'Comisión Estatal Para el Desarrollo Sostenible de los Pueblos Indígenas': 'CPI',
        'Consejo de Ciencia, Tecnología e Innovación de Hidalgo': 'CCT',
        'Consejo Rector de Pachuca Ciudad del Conocimiento y la Cultura': 'CCC',
        'Museo Interactivo para la Niñez y la Juventud "El Rehilete"': 'MIR',
        'Secretaría Técnica del Sistema Estatal Anticorrupción': 'SEA',
        'Distrito de Educación, Salud, Ciencia, Tecnología e Innovación': 'DSC',
        'Sistema para el Desarrollo Integral de las Familia del Estado de Hidalgo': 'DIF',
        'Universidad Digital del Estado de Hidalgo': 'UDH',
        # Add all other organisms here...
    },
    'Ayuntamiento': {
        '001 Acatlán': '001',
        '002 Acaxochitlán': '002',
        '003 Actopan': '003',
        '004 Agua Blanca de Iturbide': '004',
        '005 Ajacuba': '005',
        '006 Alfajayucan': '006',
        '007 Almoloya': '007',
        '008 Apan': '008',
        '009 El Arenal': '009',
        '010 Atitalaquia': '010',
        '011 Atlapexco': '011',
        '012 Atotonilco el Grande': '012',
        '013 Atotonilco de Tula': '013',
        '014 Calnali': '014',
        '015 Cardonal': '015',
        '016 Cuautepec de Hinojosa': '016',
        '017 Chapantongo': '017',
        '018 Chapulhuacán': '018',
        '019 Chilcuautla': '019',
        '020 Eloxochitlán': '020',
        '021 Emiliano Zapata': '021',
        '022 Epazoyucan': '022',
        '023 Francisco I. Madero': '023',
        '024 Huasca de Ocampo': '024',
        '025 Huautla': '025',
        '026 Huazalingo': '026',
        '027 Huehuetla': '027',
        '028 Huejutla de Reyes': '028',
        '029 Huichapan': '029',
        '030 Ixmiquilpan': '030',
        '031 Jacala de Ledezma': '031',
        '032 Jaltocán': '032',
        '033 Juárez Hidalgo': '033',
        '034 Lolotla': '034',
        '035 Metepec': '035',
        '036 San Agustín Metzquititlán': '036',
        '037 Metztitlán': '037',
        '038 Mineral del Chico': '038',
        '039 Mineral del Monte': '039',
        '040 La Misión': '040',
        '041 Mixquiahuala de Juárez': '041',
        '042 Molango de Escamilla': '042',
        '043 Nicolás Flores': '043',
        '044 Nopala de Villagrán': '044',
        '045 Omitlán de Juárez': '045',
        '046 San Felipe Orizatlán': '046',
        '047 Pacula': '047',
        '048 Pachuca de Soto': '048',
        '049 Pisaflores': '049',
        '050 Progreso de Obregón': '050',
        '051 Mineral de la Reforma': '051',
        '052 San Agustín Tlaxiaca': '052',
        '053 San Bartolo Tutotepec': '053',
        '054 San Salvador': '054',
        '055 Santiago de Anaya': '055',
        '056 Santiago Tulantepec de Lugo Guerrero': '056',
        '057 Singuilucan': '057',
        '058 Tasquillo': '058',
        '059 Tecozautla': '059',
        '060 Tenango de Doria': '060',
        '061 Tepeapulco': '061',
        '062 Tepehuacán de Guerrero': '062',
        '063 Tepeji del Río de Ocampo': '063',
        '064 Tepetitlán': '064',
        '065 Tetepango': '065',
        '066 Villa de Tezontepec': '066',
        '067 Tezontepec de Aldama': '067',
        '068 Tianguistengo': '068',
        '069 Tizayuca': '069',
        '070 Tlahuelilpan': '070',
        '071 Tlahuiltepa': '071',
        '072 Tlanalapa': '072',
        '073 Tlanchinol': '073',
        '074 Tlaxcoapan': '074',
        '075 Tolcayuca': '075',
        '076 Tula de Allende': '076',
        '077 Tulancingo de Bravo': '077',
        '078 Xochiatipan': '078',
        '079 Xochicoatlán': '079',
        '080 Yahualica': '080',
        '081 Zacualtipán de Ángeles': '081',
        '082 Zapotlán de Juárez': '082',
        '083 Zempoala': '083',
        '084 Zimapán': '084',
    }
}

sector_codes = {
    'Agua': '1a',
    'Comunicaciones y transportes': '1b',
    'Electricidad': '1c',
    'Hidrocarburos': '1d',
    'Turismo': '1e',
    'Educación': '2a',
    'Ciencia y tecnología': '2b',
    'Cultura': '2c',
    'Deportes': '2d',
    'Salud': '2e',
    'Seguridad social': '2f',
    'Urbanización y vivienda': '2g',
    'Asistencia social': '2h',
    'Seguridad nacional': '3a',
    'Seguridad pública': '3b',
    'Procuración de justicia': '3c',
    'Otros relacionados con el desarrollo económico y social': '3d',
    'Gubernamental, Oficinas administrativas': '4a',
    'No identificados en las clasificaciones anteriores': '5a',
}

unidadResponsable = {
    'Secretaría del Despacho de la Persona Titular del Poder Ejecutivo del Estado': '10',
    'Secretaría de Gobierno': '11',
    'Secretaría de Hacienda': '12',
    'Secretaría de Bienestar e Inclusión Social': '13',
    'Secretaría de Infraestructura Pública y Desarrollo Urbano Sostenible': '15',
    'Secretaría de Medio Ambiente y Recursos Naturales': '16',
    'Secretaría de Desarrollo Económico': '17',
    'Secretaría de Agricultura y Desarrollo Rural': '18',
    'Secretaría de Turismo': '19',
    'Secretaría de Contraloría': '20',
    'Secretaría de Educación Pública': '21',
    'Secretaría de Salud': '22',
    'Secretaría de Seguridad Pública': '23',
    'Secretaría del Trabajo y Previsión Social': '24',
    'Secretaría de Movilidad y Transporte': '26',
    'Secretaría de Cultura': '27',
    'Unidad de Planeación y Prospectiva': '28',
    'Oficialía Mayor': '29',
    'Procuraduría General de Justicia': '20',
    'Organismos Descentralizados': '40',
    'Organismos Descentralizados no Sectorizados': '50'
}

unidadPresupuestal = {
    '01. Secretaría del Despacho de la Persona Titular del Poder Ejecutivo del Estado': '01',
    '02. Dirección General de Relaciones Públicas': '02',
    '03. Secretaría Técnica del Despacho del Gobernador': '15',
    '04. Dirección General de Estudios Legislativos': '16',
    '05. Coordinación de Agenda y Audiencia Pública': '17',
    '06. Dirección General de Giras': '18',
    '07. Dirección General de Atención al Pueblo': '19',
    '08. Dirección General de Desarrollo Institucional': '20',
    '09. Coordinación de Seguimiento': '21',
    '10. Coordinación de Gestión y Vinculación de Proyectos Especiales': '22',
    '11. Coordinación de Operación Institucional': '23',
    '01. Secretaría de Gobierno': '01',
    '02. Subsecretaría de Gobernación': '02',
    '03. Dirección General de Investigaciones Políticas y Sociales': '04',
    '04. Dirección General de Asuntos Agrarios': '09',
    '05. Subsecretaría de Gobierno en la Huasteca Hidalguense': '10',
    '06. Subsecretaría de Gobierno en el Valle del Mezquital': '12',
    '07. Subsecretaría de Desarrollo Político': '13',
    '08. Dirección General de Desarrollo Político': '14',
    '09. Coordinación General Jurídica': '15',
    '10. Dirección General Jurídica': '16',
    '11. Subsecretaría de Protección Civil y Gestión de Riesgos': '17',
    '12. Dirección General de Protección Civil y Gestión de Riesgos': '18',
    '13. Central Estatal de Información, Investigación e Inteligencia': '19',
    '14. Consejo Estatal de Población': '24',
    '15. Instituto de la Defensoría Pública del Estado de Hidalgo': '27',
    '16. Dirección General del Mando Coordinado': '28',
    '17. Dirección General del Instituto de la Función Registral': '29',
    '18. Secretaría Ejecutiva del Sistema Estatal de Protección Integral de los derechos de Niñas, Niños y Adolescentes del Estado de Hidalgo': '30',
    '19. Secretariado Ejecutivo del Consejo Estatal de Seguridad Pública': '31',
    '20. Dirección General de Asuntos Religiosos': '33',
    '21. Dirección General de Unidades de Servicios Estatales': '34',
    '22. Coordinación General de Comunicación Gubernamental': '35',
    '23. Dirección General de Derechos Humanos': '36',
    '24. Dirección General del Registro del Estado Familiar': '37',
    '25. Dirección General de Archivo General de Notarías': '38',
    '26. Comisión de Búsqueda de Personas del Estado de Hidalgo': '39',
    '27. Dirección General Editorial': '40',
    '01. Secretaría de Hacienda': '01',
    '02. Coordinación de Planeación Financiera': '02',
    '03. Procuraduría Fiscal del Estado de Hidalgo': '03',
    '04. Unidad Técnica de Evaluación del Desempeño': '05',
    '05. Subsecretaría de Egresos': '08',
    '06. Dirección General de Contabilidad Gubernamental': '09',
    '07. Dirección General de Tesorería': '10',
    '08. Dirección General de Normatividad Contable Presupuestal': '11',
    '09. Dirección General de Atención y Seguimiento a Auditorías': '13',
    '10. Subsecretaría de Ingresos': '14',
    '11. Dirección General de Auditoría Fiscal': '15',
    '12. Dirección General de Recaudación': '16',
    '13. Coordinación de Tecnologías de la Información': '23',
    '14. Dirección General de Atención al Contribuyente': '25',
    '15. Coordinación del Gasto de Inversión': '26',
    '16. Subsecretaría de Programación y Presupuesto del Gasto de Inversión': '27',
    '17. Dirección General de Programación': '28',
    '18. Dirección General de Validación Técnica de Estudios y Proyectos': '29',
    '19. Dirección General de Monitoreo y Seguimiento al Recurso Público': '30',
    '20. Coordinación de Representación Institucional': '31',
    '21. Unidad de Inteligencia Patrimonial y Económica': '32',
    '22. Dirección General de Administración': '33',

    
    '01. Secretaría de Bienestar e Inclusión Social': '01',
    '02. Dirección General de Fomento Artesanal': '02',
    '03. Subsecretaría de Inclusión y Desarrollo': '03',
    '04. Dirección General de Operación y Logística de Programas': '04',
    '05. Dirección General de Atención al Migrante': '05',
    '06. Dirección General de Asistencia, Atención y Protección': '06',
    '07. Dirección General de Prospectiva, Planeación y Evaluación de los Programas Sociales': '07',
    '08. Subsecretaría de Participación Social y Fomento Artesanal': '08',
    '09. Dirección General de Inclusión para las Personas con Discapacidad': '09',
    '10. Subsecretaría de Desarrollo Social y Humano': '10',
    '01. Secretaría de Infraestructura Pública y Desarrollo Urbano Sostenible': '01',
    '02. Subsecretaría de Infraestructura Pública': '02',
    '03. Dirección General de Obras Públicas e Infraestructura': '03',
    '04. Dirección General de Infraestructura y Vías de Comunicación': '04',
    '05. Dirección General de Conservación de Carreteras Estatales': '05',
    '06. Subsecretaría de Desarrollo Urbano Sostenible': '06',
    '07. Dirección General de Imagen y Desarrollo Urbano Sostenible': '07',
    '08. Subsecretaría de Gestión de Proyectos': '08',
    '09. Dirección General de Estudios y Proyectos': '09',
    '10. Dirección General de Supervisión Estratégica y Evaluación': '10',
    '11. Dirección General de Tecnologías de Información y Mejora Continua': '11',
    '12. Dirección General de Asuntos Jurídicos': '12',
    '13. Dirección General de Administración': '13',
    '14. Dirección General de Atención y Vinculación Institucional': '14',
    '01. Secretaría de Medio Ambiente y Recursos Naturales': '01',
    '02. Subsecretaría de Política Ambiental': '02',
    '03. Dirección General de Ordenamiento Ecológico Territorial': '03',
    '04. Dirección General de Recursos Naturales': '04',
    '05. Dirección General de Gestión de Calidad del Aire': '05',
    '06. Consejo de Administración del Parque Nacional "El Chico"': '06',
    '07. Procuraduría Estatal de Protección al Ambiente': '07',
    '08. Dirección General de Normatividad Ambiental': '08',
    '09. Dirección General de Cuencas y Planeación Hídrica': '09',
    '10. Subsecretaría de Sustentabilidad y Cambio Climático': '10',
    '11. Dirección General de Cambio Climático': '11',
    '01. Secretaría de Desarrollo Económico': '01',
    '02. Subsecretaría de Inversiones y Economía Sectorial': '02',
    '03. Dirección General de Economía Sectorial': '03',
    '04. Dirección General de Inversiones': '04',
    '05. Subsecretaría de Fomento Económico': '05',
    '06. Dirección General de Fomento al Empleo': '06',
    '07. Dirección General de Fomento Económico': '07',
    '01. Secretaría de Agricultura y Desarrollo Rural': '01',
    '02. Subsecretaría de Desarrollo Agropecuario': '02',
    '03. Dirección General de Agricultura': '03',
    '04. Dirección General de Ganadería': '04',
    '05. Dirección General de Desarrollo Rural': '05',
    '06. Dirección General de Silvicultura, Fruticultura, Acuacultura y del Maguey': '06',
    '07. Dirección General de Infraestructura y Maquinaria': '07',
    '08. Subsecretaría de Agronegocios': '08',
    '09. Dirección General de Comercialización y Mercadotecnia': '09',
    '10. Subsecretaría de Planeación y Evaluación Sectorial': '10',
    '11. Dirección General de Evaluación y Programas Estratégicos': '11',
    '12. Dirección General de Fomento al Crédito': '12',
    '13. Dirección General de Fomento Lechero': '13',
    '14. Dirección General de Desarrollo de la Cafeticultura': '14',
    '01. Secretaría de Turismo': '01',
    '02. Dirección General de Productos Turísticos y Pueblos Mágicos': '02',
    '03. Dirección General de Promoción y Mercadotecnia': '03',
    '04. Dirección General de Formación y Competitividad Turística': '04',
    '05. Dirección General de Programas Turísticos y Alianzas Estratégicas': '05',
    '06. Dirección de Planeación y Evaluación': '06',
    '07. Subsecretaría de Turismo': '07',
    '08. Dirección de Innovación, Desarrollo de Productos Turísticos e Infraestructura': '08',
    '01. Secretaría de Contraloría': '01',
    '02. Dirección General de Órganos de Control y Vigilancia': '02',
    '03. Dirección General de Inspección y Vigilancia de Obras y Acciones': '03',
    '04. Dirección General de Normatividad': '04',
    '05. Dirección General de Responsabilidades Administrativas': '05',
    '06. Dirección General de Vinculación': '06',
    '07. Dirección General de Auditoría Gubernamental': '07',
    '01. Secretaría de Educación Pública': '01',
    '02. Subsecretaría de Administración y Finanzas': '02',
    '03. Subsecretaría de Educación Básica': '03',
    '04. Subsecretaría de Educación Media Superior y Superior': '04',
    '05. Subsecretaría de Planeación y Evaluación': '05',
    '06. Centro Estatal de Lenguas y Culturas Indígenas': '06',
    '01. Secretaría de Salud': '01',
    '02. Subsecretaría de Salud Pública': '02',
    '03. Subsecretaría de Servicios de Salud': '03',
    '04. Subsecretaría de Administración, Finanzas y Planeación': '04',
    '05. Comisión de Arbitraje Médico del Estado de Hidalgo': '05',
    '06. Comisión para la Protección contra Riesgos Sanitarios del Estado de Hidalgo': '06',
    '07. Dirección General de Proyectos Estratégicos de Salud': '07',
    '08. Centro Estatal de Trasplantes de Órganos, Tejidos y Células de Humanos para el Estado de Hidalgo': '08',
    '01. Secretaría de Seguridad Pública': '01',
    '02. Subsecretaría de Prevención y Reinserción Social': '02',
    '03. Dirección General de Prevención y Reinserción Social': '03',
    '04. Subsecretaría de C5i': '04',
    '05. Dirección General de Servicios Aéreos': '05',
    '06. Subsecretaría de Prevención y Coordinación Institucional': '06',
    '07. Dirección General del Centro Estatal de Prevención Social de la Violencia y la Delincuencia': '07',
    '08. Dirección General de Asuntos Jurídicos y Derechos Humanos': '08',
    '09. Subsecretaría de Operación Policial': '09',
    '10. Instituto de Formación Profesional': '10',
    '11. Centro Estatal de Evaluación y Control de Confianza': '11',
    '12. Unidad de Medidas Cautelares': '12',
    '13. Dirección General de Ayudantía Personal': '13',
    '14. Dirección General de Supervisión e Inspección Interna': '14',
    '01. Secretaría del Trabajo y Previsión Social': '01',
    '02. Dirección General del Trabajo y Previsión Social': '02',
    '03. Dirección General del Servicio Nacional de Empleo': '03',
    '04. Junta Local de Conciliación y Arbitraje': '04',
    '05. Tribunal de Arbitraje': '05',
    '06. Procuraduría Estatal de la Defensa del Trabajo': '06',
    '01. Secretaría de Movilidad y Transporte': '01',
    '02. Subsecretaría de Movilidad y Transporte': '02',
    '03. Dirección General de Normatividad': '03',
    '04. Dirección General de Movilidad Sustentable': '04',
    '01. Secretaría de Cultura': '01',
    '02. Dirección General de Diversidad Cultural y Fomento a la Lectura, Escritura y Oralidad': '02',
    '03. Dirección General de Cultura Digital': '03',
    '04. Dirección General de Vinculación, Programación y Difusión Cultural': '04',
    '05. Subsecretaría de Desarrollo Cultural': '05',
    '06. Dirección General de Cultura Originaria, Popular y Urbana': '06',
    '07. Dirección General de Patrimonio Cultural': '07',
    '01. Unidad de Planeación y Prospectiva': '01',
    '02. Coordinación General de Normatividad y Entidades Paraestatales': '02',
    '03. Dirección General de Consulta y Normatividad': '03',
    '04. Dirección General de Control y Seguimiento a Entidades Paraestatales': '04',
    '05. Coordinación General de Planeación y Proyectos': '05',
    '06. Dirección General de Análisis Geográfico y Mejora a las Políticas Públicas': '06',
    '07. Dirección General de Planeación y Participación Ciudadana': '07',
    '08. Dirección General de Desarrollo Regional y Metropolitano': '08',
    '09. Coordinación General de Evaluación y Políticas Públicas': '09',
    '10. Dirección General de Evaluación': '10',
    '11. Dirección General de Monitoreo': '11',
    '12. Dirección General de Percepción e Impacto Ciudadano': '12',
    '13. Dirección General de Proyectos, Estudios y Prospectiva': '13',
    '14. Comisión Estatal de Mejora Regulatoria': '14',
    '01. Oficialía Mayor': '01',
    '02. Dirección General de Compras Públicas': '02',
    '03. Dirección General de Patrimonio Inmobiliario': '03',
    '04. Dirección General de Recursos Materiales y Servicios': '04',
    '05. Dirección General de Recursos Humanos': '05',
    '06. Archivo General del Estado de Hidalgo': '06',
    '07. Dirección General de Innovación Gubernamental': '07',
    '08. Coordinación General de la Oficialía Mayor': '08',
    '01. Procuraduría General de Justicia': '01',
    '02. Subprocuraduría Oriente': '02',
    '03. Dirección General del Sistema Mixto': '03',
    '04. Fiscalía Especializada en Delitos Electorales': '04',
    '05. Subprocuraduría de Delitos de Género, Desaparición de Personas e Impacto Social': '05',
    '06. Visitaduría General': '06',
    '07. Unidad Especializada en el Combate al Secuestro': '07',
    '08. Oficialía Mayor': '08',
    '09. Subprocuraduría Poniente': '09',
    '10. Fiscalía Especializada en Delitos de Corrupción': '10',
    '11. Subprocuraduría Jurídica y de Derechos Humanos': '11',
    '12. Unidad de Recuperación de Vehículos': '12',
    '13. Agencia de investigación Criminal': '13',
    '14. Centro de Justicia Restaurativa': '14',
    '15. Órgano Interno de Control': '15',
    '01. Radio y Televisión de Hidalgo': '01',
    '02. Instituto Hidalguense para el Desarrollo Municipal': '02',
    '03. Instituto Catastral del Estado de Hidalgo': '03',
    '04. Instituto Hidalguense de las Mujeres': '04',
    '05. Instituto Hidalguense de la Juventud': '05',
    '06. Instituto para la Atención de las y los Adultos Mayores del Estado de Hidalgo': '06',
    '07. Centro Estatal de Maquinaria para el Desarrollo': '07',
    '08. Comisión Estatal de Vivienda': '08',
    '09. Comisión Estatal del Agua y Alcantarillado': '09',
    '10. Comisión de Agua y Alcantarillado de Sistemas Intermunicipales': '10',
    '11. Comisión de Agua y Alcantarillado del Sistema Valle del Mezquital': '11',
    '12. Instituto de Vivienda, Desarrollo Urbano y Asentamientos Humanos': '12',
    '13. Sistema de Autopistas, Servicios Conexos y Auxiliares del Estado de Hidalgo': '13',
    '14. Corporación Internacional Hidalgo': '14',
    '15. Corporación de Fomento de Infraestructura Industrial': '15',
    '16. Operadora de Eventos del Estado de Hidalgo': '16',
    '17. Instituto Hidalguense de Competitividad Empresarial': '17',
    '18. Agencia de Desarrollo Valle de Plata': '18',
    '19. Consejo Estatal para la Cultura y las Artes de Hidalgo': '19',
    '20. Instituto Hidalguense de Educación': '20',
    '21. Instituto Hidalguense de Educación para Adultos': '21',
    '22. Universidad Politécnica de Tulancingo': '22',
    '23. Universidad Politécnica de Pachuca': '23',
    '24. Universidad Politécnica de Francisco I. Madero': '24',
    '25. Universidad Politécnica de Huejutla': '25',
    '26. Universidad Politécnica Metropolitana de Hidalgo': '26',
    '27. Universidad Tecnológica de Tula–Tepeji': '27',
    '28. Universidad Tecnológica de Tulancingo': '28',
    '29. Universidad Tecnológica de la Huasteca Hidalguense': '29',
    '30. Universidad Tecnológica del Valle del Mezquital': '30',
    '31. Universidad Tecnológica de la Sierra Hidalguense': '31',
    '32. Universidad Tecnológica de la Zona Metropolitana del Valle de México': '32',
    '33. Instituto Tecnológico Superior de Huichapan': '33',
    '34. Instituto Tecnológico Superior del Occidente del Estado de Hidalgo': '34',
    '35. Instituto Tecnológico Superior del Oriente del Estado de Hidalgo': '35',
    '36. Universidad Intercultural del Estado de Hidalgo': '36',
    '37. Colegio de Bachilleres del Estado de Hidalgo': '37',
    '38. Bachillerato del Estado de Hidalgo': '38',
    '39. Colegio de Estudios Científicos y Tecnológicos del Estado de Hidalgo': '39',
    '40. Colegio de Educación Profesional Técnica del Estado de Hidalgo': '40',
    '41. El Colegio del Estado de Hidalgo': '41',
    '42. Escuela de Música del Estado de Hidalgo': '42',
    '43. Instituto Hidalguense de Financiamiento a la Educación Superior': '43',
    '44. Instituto Hidalguense del Deporte': '44',
    '45. Instituto Hidalguense de la Infraestructura Física Educativa': '45',
    '46. Servicios de Salud de Hidalgo': '46',
    '47. Instituto de Capacitación para el Trabajo del Estado de Hidalgo': '47',
    '48. Policía Industrial Bancaria del Estado de Hidalgo': '48',
    '49. Centro de Justicia para Mujeres del Estado de Hidalgo': '49',
    '50. Sistema de Transporte Convencional de Hidalgo': '50',
    '51. Sistema Integrado de Transporte Masivo de Hidalgo': '51',
    '52. Universidad Tecnológica Minera de Zimapán': '52',
    '53. Universidad Tecnológica de Mineral de la Reforma': '53',
    '54. Universidad Politécnica de la Energía': '54',
    '55. Ciudad de las Mujeres': '55',
    '56. Agencia Estatal de Energía de Hidalgo': '56',
    '57. Centro de Conciliación Laboral del Estado de Hidalgo': '57',
    '58. Comisión Estatal de Biodiversidad de Hidalgo': '58',
    '59. Universidad Digital del Estado de Hidalgo': '59',
    '60. Comisión Ejecutiva de Atención a Víctimas del Estado de Hidalgo': '60',
    '61. Instituto Hidalguense para Devolver al Pueblo lo Robado': '61',
    '01. Secretaría Técnica del Sistema Estatal Anticorrupción de Hidalgo': '01',
    '02. Sistema para el Desarrollo Integral de la Familia del Estado de Hidalgo': '02',
    '03. Comisión Estatal para el Desarrollo Sostenible de los Pueblos Indígenas (CEDSPI)': '03',
    '04. Consejo de Ciencia, Tecnología e Innovación de Hidalgo (CITNOVA)': '04',
    '05. Universidad Autónoma del Estado de Hidalgo': '05',
    '06. Museo Interactivo para la Niñez y la Juventud Hidalguense “El Rehilete”': '06',
    '07. Consejo Ejecutivo del Complejo Científico y Tecnológico Sincrotrón en el Estado de Hidalgo': '07',
    '08. Coordinación General del Distrito de Educación, Salud, Ciencia, Tecnología e Innovación': '08'
}



from .models import CedulaRegistro

unidadResponsable = {
    'Secretaría del Despacho de la Persona Titular del Poder Ejecutivo del Estado': '10',
    'Secretaría de Gobierno': '11',
    'Secretaría de Hacienda': '12',
    'Secretaría de Bienestar e Inclusión Social': '13',
    'Secretaría de Infraestructura Pública y Desarrollo Urbano Sostenible': '15',
    'Secretaría de Medio Ambiente y Recursos Naturales': '16',
    'Secretaría de Desarrollo Económico': '17',
    'Secretaría de Agricultura y Desarrollo Rural': '18',
    'Secretaría de Turismo': '19',
    'Secretaría de Contraloría': '20',
    'Secretaría de Educación Pública': '21',
    'Secretaría de Salud': '22',
    'Secretaría de Seguridad Pública': '23',
    'Secretaría del Trabajo y Previsión Social': '24',
    'Secretaría de Movilidad y Transporte': '26',
    'Secretaría de Cultura': '27',
    'Unidad de Planeación y Prospectiva': '28',
    'Oficialía Mayor': '29',
    'Procuraduría General de Justicia': '20',
    'Organismos Descentralizados': '40',
    'Organismos Descentralizados no Sectorizados': '50'
}

def generate_proj_investment_id(unidad_responsable, fecha_registro):
    # Obtener la sigla para la unidad responsable
    sigla = unidadResponsable.get(unidad_responsable, 'UNK')
    
    # Formatear la fecha de registro a 'ddmmyy'
    fecha_formateada = fecha_registro.strftime('%d%m%y')
    
    # Obtener el número consecutivo
    existing_ids_count = CedulaRegistro.objects.filter(projInvestment_id__startswith=sigla + fecha_formateada).count()
    consecutive_number = str(existing_ids_count + 1).zfill(4)  # Consecutivo con 4 dígitos

    # Construir el ID final
    proj_investment_id = f"{sigla}{fecha_formateada}{consecutive_number}"

    return proj_investment_id