# utils.py

siglas = {
    'Dependencia': {
        'Secretaría del Despacho del Gobernador': 'SDG',
        'Oficialía Mayor': 'OFM',
        'Unidad de Planeación y Prospectiva': 'UPL',
        'Secretaría de Gobierno': 'GOB',
        'Secretaría de Hacienda': 'HAC',
        'Secretaría de Bienestar e Inclusión Social': 'SBI',
        'Secretaría de Infraestructura Pública y Desarrollo Urbano Sostenible': 'SIP',
        'Secretaría de Desarrollo Económico': 'SDE',
        'Secretaría de Medio Ambiente y Recursos Naturales': 'SMR',
        'Secretaría de Agricultura y Desarrollo Rural': 'SAD',
        'Secretaría de Turismo': 'TUR',
        'Secretaría de Contraloría': 'CON',
        'Secretaría de Educación Pública': 'SEP',
        'Secretaría de Salud': 'SLD',
        'Secretaría de Seguridad Pública': 'SEG',
        'Secretaría del Trabajo y Previsión Social': 'STP',
        'Secretaría de Movilidad y Transporte': 'SMT',
        'Secretaría de Cultura': 'CUL',
        'Procuraduría General de Justicia': 'PGJ',
        # Add all other dependencies here...
    },
    'Organismo': {
        'Centro de Justicia para Mujeres del Estado de Hidalgo': 'CJM',
        'Ciudad de las Mujeres': 'CMU',
        'Instituto Hidalguense de las Mujeres': 'IMU',
        'Instituto Hidalguense para el Desarrollo Municipal': 'IND',
        'Instituto Catastral del Estado de Hidalgo': 'ICA',
        'Instituto para Devolver al Pueblo lo Robado': 'IPR',
        'Centro Estatal de Maquinaria para el Desarrollo': 'CMD',
        'Comisión de Agua y Alcantarillado del Sistema Valle del Mezquital': 'CAV',
        'Comisión de Agua y Alcantarillado de Sistemas Intermunicipales': 'CAI',
        'Comisión Estatal del Agua y Alcantarillado': 'CEA',
        'Comisión Estatal de Vivienda': 'CEV',
        'Policía Industrial Bancaria del Estado de Hidalgo': 'PIB',
        'Consejo Estatal para la Cultura y las Artes de Hidalgo': 'CCA',
        'Escuela de Música del Estado de Hidalgo': 'EMH',
        'Servicios de Salud de Hidalgo': 'SSH',
        'Agencia de Desarrollo Valle de Plata': 'AVP',
        'Agencia Estatal de Energía': 'AEE',
        'Corporación de Fomento de Infraestructura Industrial': 'FII',
        'Corporación Internacional Hidalgo': 'CIH',
        'Instituto Hidalguense de Competitividad Empresarial': 'IHC',
        'Comisión Estatal de Biodiversidad de Hidalgo': 'COE',
        'Centro de Conciliación Laboral del Estado de Hidalgo': 'CLH',
        'Instituto de Capacitación para el Trabajo del Estado de Hidalgo': 'CTH',
        'Operadora de Eventos del Estado de Hidalgo': 'OEH',
        'Bachillerato del Estado de Hidalgo': 'BEH',
        'Colegio de Bachilleres del Estado de Hidalgo': 'CBH',
        'Colegio de Educación Profesional Técnica del Estado de Hidalgo': 'EPT',
        'Colegio de Estudios Científicos y Tecnológicos del Estado de Hidalgo': 'ECT',
        'El Colegio del Estado de Hidalgo': 'CEH',
        'Instituto Hidalguense de Educación': 'IHE',
        'Instituto Hidalguense de Educación para Adultos': 'IHA',
        'Instituto Hidalguense de Financiamiento a la Educación Superior': 'IHF',
        'Instituto Hidalguense de la Infraestructura Física Educativa': 'IFE',
        'Instituto Hidalguense del Deporte': 'IHD',
        'Instituto Tecnológico Superior de Huichapan': 'ITH',
        'Instituto Tecnológico Superior del Occidente del Estado de Hidalgo': 'ITS',
        'Instituto Tecnológico Superior del Oriente del Estado de Hidalgo': 'ITE',
        'Radio y Televisión de Hidalgo': 'RTH',
        'Universidad Intercultural del Estado de Hidalgo': 'UIC',
        'Universidad Politécnica de Francisco I. Madero': 'UPF',
        'Universidad Politécnica de Huejutla': 'UPH',
        'Universidad Politécnica de la Energía': 'UPE',
        'Universidad Politécnica de Pachuca': 'UPP',
        'Universidad Politécnica de Tulancingo': 'UPT',
        'Universidad Politécnica Metropolitana de Hidalgo': 'UPM',
        'Universidad Tecnológica de la Huasteca Hidalguense': 'UTH',
        'Universidad Tecnológica de la Sierra Hidalguense': 'UTS',
        'Universidad Tecnológica de la Zona Metropolitana del Valle de México': 'UTV',
        'Universidad Tecnológica de Mineral de la Reforma': 'UTM',
        'Universidad Tecnológica de Tulancingo': 'UTT',
        'Universidad Tecnológica de Tula-Tepeji': 'UTU',
        'Universidad Tecnológica del Valle del Mezquital': 'UVM',
        'Universidad Tecnológica Minera de Zimapán': 'UTZ',
        'Instituto Hidalguense de la Juventud': 'IHJ',
        'Instituto para la Atención de las y los Adultos Mayores del Estado de Hidalgo': 'IAA',
        'Sistema de Convencional': 'STC',
        'Sistema de Masivo': 'STM',
        'Comisión Estatal Para el Desarrollo Sostenible de los Pueblos Indígenas': 'CPI',
        'Consejo de Ciencia, Tecnología e Innovación de Hidalgo': 'CCT',
        'Consejo Rector de Pachuca Ciudad del Conocimiento y la Cultura': 'CCC',
        'Museo Interactivo para la Niñez y la Juventud "El Rehilete"': 'MIR',
        'Secretaría Técnica del Sistema Estatal Anticorrupción': 'SEA',
        'Distrito de Educación, Salud, Ciencia, Tecnología e Innovación': 'DSC',
        'Sistema para el Desarrollo Integral de las Familia del Estado de Hidalgo': 'DIF',
        'Universidad Digital del Estado de Hidalgo': 'UDH',
        # Add all other organisms here...
    },
    'Municipio': {
        'Acatlán': '001',
        'Acaxochitlán': '002',
        'Actopan': '003',
        'Agua Blanca de Iturbide': '004',
        'Ajacuba': '005',
        'Alfajayucan': '006',
        'Almoloya': '007',
        'Apan': '008',
        'El Arenal': '009',
        'Atitalaquia': '010',
        'Atlapexco': '011',
        'Atotonilco el Grande': '012',
        'Atotonilco de Tula': '013',
        'Calnali': '014',
        'Cardonal': '015',
        'Cuautepec de Hinojosa': '016',
        'Chapantongo': '017',
        'Chapulhuacán': '018',
        'Chilcuautla': '019',
        'Eloxochitlán': '020',
        'Emiliano Zapata': '021',
        'Epazoyucan': '022',
        'Francisco I. Madero': '023',
        'Huasca de Ocampo': '024',
        'Huautla': '025',
        'Huazalingo': '026',
        'Huehuetla': '027',
        'Huejutla de Reyes': '028',
        'Huichapan': '029',
        'Ixmiquilpan': '030',
        'Jacala de Ledezma': '031',
        'Jaltocán': '032',
        'Juárez Hidalgo': '033',
        'Lolotla': '034',
        'Metepec': '035',
        'San Agustín Metzquititlán': '036',
        'Metztitlán': '037',
        'Mineral del Chico': '038',
        'Mineral del Monte': '039',
        'La Misión': '040',
        'Mixquiahuala de Juárez': '041',
        'Molango de Escamilla': '042',
        'Nicolás Flores': '043',
        'Nopala de Villagrán': '044',
        'Omitlán de Juárez': '045',
        'San Felipe Orizatlán': '046',
        'Pacula': '047',
        'Pachuca de Soto': '048',
        'Pisaflores': '049',
        'Progreso de Obregón': '050',
        'Mineral de la Reforma': '051',
        'San Agustín Tlaxiaca': '052',
        'San Bartolo Tutotepec': '053',
        'San Salvador': '054',
        'Santiago de Anaya': '055',
        'Santiago Tulantepec de Lugo Guerrero': '056',
        'Singuilucan': '057',
        'Tasquillo': '058',
        'Tecozautla': '059',
        'Tenango de Doria': '060',
        'Tepeapulco': '061',
        'Tepehuacán de Guerrero': '062',
        'Tepeji del Río de Ocampo': '063',
        'Tepetitlán': '064',
        'Tetepango': '065',
        'Villa de Tezontepec': '066',
        'Tezontepec de Aldama': '067',
        'Tianguistengo': '068',
        'Tizayuca': '069',
        'Tlahuelilpan': '070',
        'Tlahuiltepa': '071',
        'Tlanalapa': '072',
        'Tlanchinol': '073',
        'Tlaxcoapan': '074',
        'Tolcayuca': '075',
        'Tula de Allende': '076',
        'Tulancingo de Bravo': '077',
        'Xochiatipan': '078',
        'Xochicoatlán': '079',
        'Yahualica': '080',
        'Zacualtipán de Ángeles': '081',
        'Zapotlán de Juárez': '082',
        'Zempoala': '083',
        'Zimapán': '084',
        # Add all other municipalities here...
    }
}
