# Generated by Django 5.0.6 on 2024-07-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('project_name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('tipo_proyecto', models.CharField(max_length=255)),
                ('tipo_entidad', models.CharField(max_length=255)),
                ('dependencia', models.CharField(blank=True, max_length=255, null=True)),
                ('organismo', models.CharField(blank=True, max_length=255, null=True)),
                ('municipioEnd', models.CharField(blank=True, max_length=255, null=True)),
                ('peticion_personal', models.CharField(blank=True, max_length=255, null=True)),
                ('unidad_responsable', models.CharField(max_length=255)),
                ('unidad_presupuestal', models.CharField(max_length=255)),
                ('ramo_presupuestal', models.CharField(max_length=255)),
                ('monto_federal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_estatal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_municipal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_otros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inversion_estimada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descripcion', models.TextField()),
                ('situacion_sin_proyecto', models.TextField()),
                ('objetivos', models.TextField()),
                ('metas', models.TextField()),
                ('gasto_programable', models.CharField(max_length=255)),
                ('programa_presupuestario', models.CharField(max_length=255)),
                ('beneficiarios', models.IntegerField(blank=True, null=True)),
                ('alineacion_normativa', models.TextField()),
                ('region', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('municipio_impacto', models.JSONField(blank=True, null=True)),
                ('localidad', models.CharField(max_length=255)),
                ('barrio_colonia_ejido', models.CharField(max_length=255)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('plan_nacional', models.CharField(max_length=255)),
                ('plan_estatal', models.CharField(max_length=255)),
                ('plan_municipal', models.TextField(blank=True, null=True)),
                ('ods', models.CharField(max_length=255)),
                ('plan_sectorial', models.CharField(max_length=255)),
                ('indicadores_estrategicos', models.CharField(max_length=255)),
                ('indicadores_tacticos', models.CharField(blank=True, max_length=255, null=True)),
                ('indicadores_desempeno', models.CharField(blank=True, max_length=255, null=True)),
                ('indicadores_rentabilidad', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_inicial', models.ImageField(blank=True, null=True, upload_to='estado_inicial/')),
                ('estado_con_proyecto', models.ImageField(blank=True, null=True, upload_to='estado_con_proyecto/')),
                ('estudios_prospectivos', models.FileField(blank=True, null=True, upload_to='estudios_prospectivos/')),
                ('estudios_factibilidad', models.FileField(blank=True, null=True, upload_to='estudios_factibilidad/')),
                ('analisis_alternativas', models.FileField(blank=True, null=True, upload_to='analisis_alternativas/')),
                ('validacion_normativa', models.FileField(blank=True, null=True, upload_to='validacion_normativa/')),
                ('liberacion_derecho_via', models.FileField(blank=True, null=True, upload_to='liberacion_derecho_via/')),
                ('situacion_sin_proyecto_fotografico', models.FileField(blank=True, null=True, upload_to='situacion_sin_proyecto_fotografico/')),
                ('situacion_con_proyecto_proyeccion', models.FileField(blank=True, null=True, upload_to='situacion_con_proyecto_proyeccion/')),
                ('analisis_costo_beneficio', models.FileField(blank=True, null=True, upload_to='analisis_costo_beneficio/')),
                ('expediente_tecnico', models.FileField(blank=True, null=True, upload_to='expediente_tecnico/')),
                ('proyecto_ejecutivo', models.FileField(blank=True, null=True, upload_to='proyecto_ejecutivo/')),
                ('manifestacion_impacto_ambiental', models.FileField(blank=True, null=True, upload_to='manifestacion_impacto_ambiental/')),
                ('otros_estudios', models.FileField(blank=True, null=True, upload_to='otros_estudios/')),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
