# Generated by Django 5.0.4 on 2024-05-11 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
