# Generated by Django 5.0.6 on 2025-02-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formproject',
            name='isBlocked_situacion_actual',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='observacion_situacion_actual',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='situacion_actual',
        ),
    ]
