# Generated by Django 5.0.4 on 2024-06-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formproject',
            name='indicadores_desempeno',
            field=models.CharField(default='No definido', max_length=255),
        ),
        migrations.AddField(
            model_name='formproject',
            name='indicadores_rentabilidad',
            field=models.CharField(default='No definido', max_length=255),
        ),
        migrations.AlterField(
            model_name='formproject',
            name='municipio',
            field=models.CharField(blank=True, default='Desconocido', max_length=255, null=True),
        ),
    ]
