# Generated by Django 5.0.4 on 2024-06-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0002_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('tipo_proyecto', models.CharField(max_length=255)),
                ('dependencia', models.CharField(blank=True, max_length=255, null=True)),
                ('organismo', models.CharField(blank=True, max_length=255, null=True)),
                ('municipio', models.CharField(blank=True, max_length=255, null=True)),
                ('peticion_personal', models.CharField(blank=True, max_length=255, null=True)),
                ('monto_federal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_estatal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_municipal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_otros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descripcion', models.TextField()),
                ('situacion_sin_proyecto', models.TextField()),
                ('objetivos', models.TextField()),
                ('metas', models.TextField()),
                ('programa_presupuestario', models.CharField(max_length=255)),
                ('beneficiarios', models.IntegerField(blank=True, null=True)),
                ('alineacion_normativa', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('plan_nacional', models.CharField(max_length=255)),
                ('plan_estatal', models.CharField(max_length=255)),
                ('plan_municipal', models.CharField(blank=True, max_length=255, null=True)),
                ('ods', models.CharField(max_length=255)),
                ('plan_sectorial', models.CharField(max_length=255)),
                ('unidad_responsable', models.CharField(max_length=255)),
                ('unidad_presupuestal', models.CharField(max_length=255)),
                ('ramo_presupuestal', models.CharField(max_length=255)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('gasto_programable', models.CharField(max_length=255)),
                ('indicadores_estrategicos', models.CharField(max_length=255)),
                ('indicadores_tacticos', models.CharField(max_length=255)),
                ('indicadores_desempeno', models.TextField()),
                ('indicadores_rentabilidad', models.TextField()),
                ('estado_inicial', models.ImageField(blank=True, null=True, upload_to='estado_inicial/')),
                ('estado_con_proyecto', models.ImageField(blank=True, null=True, upload_to='estado_con_proyecto/')),
            ],
        ),
    ]
