# Generated by Django 5.0.4 on 2024-06-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0002_formproject_indicadores_desempeno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formproject',
            name='indicadores_desempeno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formproject',
            name='indicadores_rentabilidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formproject',
            name='municipio',
            field=models.CharField(default='No definido', max_length=255),
            preserve_default=False,
        ),
    ]
