# Generated by Django 5.0.4 on 2024-06-12 18:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
