# Generated by Django 5.0.6 on 2024-07-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0003_alter_formproject_analisis_alternativas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formproject',
            name='estatus',
            field=models.CharField(choices=[('Atendido', 'Atendido'), ('En Proceso', 'En Proceso'), ('Sin Avance', 'Sin Avance')], default='Sin Avance', max_length=50),
        ),
        migrations.AddField(
            model_name='formproject',
            name='porcentaje_avance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='formproject',
            name='situacion',
            field=models.CharField(choices=[('Vigente', 'Vigente'), ('Antecedente', 'Antecedente'), ('Cancelado', 'Cancelado')], default='Vigente', max_length=50),
        ),
    ]
