# Generated by Django 5.0.6 on 2025-02-07 19:01

import banco_pro.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0003_formproject_isblocked_situacion_actual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formproject',
            name='analisis_alternativas',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='analisis_costo_beneficio',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='estudios_factibilidad',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='expediente_tecnico',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='liberacion_derecho_via',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='manifestacion_impacto_ambiental',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='otros_estudios',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='proyecto_ejecutivo',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='render',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='situacion_actual',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='validacion_normativa',
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('expediente_tecnico', 'Expediente Técnico'), ('estudios_factibilidad', 'Estudios de Factibilidad'), ('analisis_alternativas', 'Análisis de Alternativas'), ('validacion_normativa', 'Validación Normativa'), ('liberacion_derecho_via', 'Liberación Derecho Vía'), ('analisis_costo_beneficio', 'Análisis Costo Beneficio'), ('proyecto_ejecutivo', 'Proyecto Ejecutivo'), ('manifestacion_impacto_ambiental', 'Manifestación Impacto Ambiental'), ('render', 'Render'), ('otros_estudios', 'Otros Estudios')], max_length=50)),
                ('file', models.FileField(upload_to=banco_pro.models.document_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='banco_pro.formproject')),
            ],
        ),
    ]
