# Generated by Django 5.0.4 on 2024-06-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0003_alter_formproject_indicadores_desempeno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formproject',
            name='municipioEnd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
