# Generated by Django 5.0.4 on 2024-06-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0004_formproject_municipioend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formproject',
            name='municipio_impacto',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
