# Generated by Django 5.0.6 on 2024-07-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0004_formproject_estatus_formproject_porcentaje_avance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formproject',
            name='retroalimentacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
