# Generated by Django 5.0.6 on 2025-02-26 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0005_formproject_last_modified_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formproject',
            name='last_modified_at',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='last_modified_by',
        ),
        migrations.DeleteModel(
            name='FormProjectHistory',
        ),
    ]
