# Generated by Django 5.2 on 2025-05-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0006_remove_formproject_last_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formproject',
            name='observacion_tiempo_ejecucion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
