# Generated by Django 5.0.6 on 2024-07-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0006_formproject_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='formproject',
            name='alineacion_normativa_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='analisis_alternativas_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='analisis_costo_beneficio_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='barrio_colonia_ejido_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='beneficiarios_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='dependencia_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='descripcion_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='estado_con_proyecto_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='estado_inicial_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='estudios_factibilidad_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='estudios_prospectivos_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='expediente_tecnico_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='gasto_programable_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='indicadores_desempeno_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='indicadores_estrategicos_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='indicadores_rentabilidad_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='indicadores_tacticos_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='inversion_estimada_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='latitud_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='liberacion_derecho_via_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='localidad_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='longitud_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='manifestacion_impacto_ambiental_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='metas_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='monto_estatal_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='monto_federal_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='monto_municipal_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='monto_otros_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='municipioEnd_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='municipio_impacto_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='municipio_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='objetivos_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='ods_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='organismo_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='otros_estudios_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='peticion_personal_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='plan_estatal_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='plan_municipal_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='plan_nacional_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='plan_sectorial_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='programa_presupuestario_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='project_name_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='proyecto_ejecutivo_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='ramo_presupuestal_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='region_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='sector_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='situacion_con_proyecto_proyeccion_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='situacion_sin_proyecto_fotografico_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='situacion_sin_proyecto_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='tipo_entidad_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='tipo_proyecto_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='unidad_presupuestal_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='unidad_responsable_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='validacion_normativa_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
