# Generated by Django 5.2 on 2025-05-03 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0007_alter_formproject_observacion_tiempo_ejecucion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formproject',
            name='isBlocked_expediente_tecnico',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='isBlocked_situacion_actual',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='observacion_expediente_tecnico',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='observacion_situacion_actual',
        ),
    ]
