# Generated by Django 5.2 on 2025-05-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0008_remove_formproject_isblocked_expediente_tecnico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('estudios_factibilidad', 'Estudios de Factibilidad'), ('analisis_alternativas', 'Análisis de Alternativas'), ('validacion_normativa', 'Validación Normativa'), ('liberacion_derecho_via', 'Liberación Derecho Vía'), ('analisis_costo_beneficio', 'Análisis Costo Beneficio'), ('proyecto_ejecutivo', 'Proyecto Ejecutivo'), ('manifestacion_impacto_ambiental', 'Manifestación Impacto Ambiental'), ('render', 'Render'), ('otros_estudios', 'Otros Estudios')], max_length=50),
        ),
        migrations.AlterField(
            model_name='formproject',
            name='isBlocked_project',
            field=models.BooleanField(default=True, help_text='Marca esta casilla para habilitar en los campos permitidos.', verbose_name='¿Liberar Formulario?'),
        ),
    ]
