# Generated by Django 5.0.6 on 2024-07-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0009_formproject_isblocked_alineacion_normativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formproject',
            name='observacion_alineacion_normativa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_analisis_alternativas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_analisis_costo_beneficio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_barrio_colonia_ejido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_beneficiarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_dependencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_estado_con_proyecto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_estado_inicial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_estatus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_estudios_factibilidad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_estudios_prospectivos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_expediente_tecnico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_gasto_programable',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_indicadores_desempeno',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_indicadores_estrategicos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_indicadores_rentabilidad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_indicadores_tacticos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_inversion_estimada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_latitud',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_liberacion_derecho_via',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_localidad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_longitud',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_manifestacion_impacto_ambiental',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_metas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_monto_estatal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_monto_federal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_monto_municipal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_monto_otros',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_municipio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_municipioEnd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_municipio_impacto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_objetivos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_ods',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_organismo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_otros_estudios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_peticion_personal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_plan_estatal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_plan_municipal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_plan_nacional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_plan_sectorial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_porcentaje_avance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_programa_presupuestario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_project_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_proyecto_ejecutivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_ramo_presupuestal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_region',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_retroalimentacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_sector',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_situacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_situacion_con_proyecto_proyeccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_situacion_sin_proyecto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_situacion_sin_proyecto_fotografico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_tipo_entidad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_tipo_proyecto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_unidad_presupuestal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_unidad_responsable',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_validacion_normativa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
