# Generated by Django 5.2 on 2025-05-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0009_alter_document_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formproject',
            name='isBlocked_project',
            field=models.BooleanField(default=True, help_text='Marca esta casilla para habilitar la edición al usuario en los campos permitidos.', verbose_name='¿Liberar Formulario?'),
        ),
    ]
