# Generated by Django 5.2 on 2025-05-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0010_alter_formproject_isblocked_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formproject',
            name='isBlocked_analisis_alternativas',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='isBlocked_analisis_costo_beneficio',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='isBlocked_estudios_factibilidad',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='isBlocked_liberacion_derecho_via',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='isBlocked_manifestacion_impacto_ambiental',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='isBlocked_otros_estudios',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='isBlocked_proyecto_ejecutivo',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='isBlocked_render',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='isBlocked_validacion_normativa',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='observacion_analisis_alternativas',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='observacion_analisis_costo_beneficio',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='observacion_estudios_factibilidad',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='observacion_liberacion_derecho_via',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='observacion_manifestacion_impacto_ambiental',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='observacion_otros_estudios',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='observacion_proyecto_ejecutivo',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='observacion_render',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='observacion_validacion_normativa',
        ),
        migrations.AlterField(
            model_name='formproject',
            name='isBlocked_project',
            field=models.BooleanField(default=True, help_text='Desmarcar esta casilla para habilitar la edición al usuario en los campos permitidos.', verbose_name='¿Liberar Formulario?'),
        ),
    ]
