# Generated by Django 5.0.6 on 2024-08-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0010_formproject_observacion_alineacion_normativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formproject',
            name='estatus',
            field=models.CharField(choices=[('Atendido', 'Atendido'), ('En Proceso', 'En Proceso'), ('Registrado', 'Registrado')], default='Registrado', max_length=50),
        ),
    ]
