# Generated by Django 5.0.6 on 2024-08-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0012_formproject_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formproject',
            name='entidadEstado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='isBlocked_entidadEstado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_entidadEstado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
