# Generated by Django 5.0.6 on 2024-08-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0013_formproject_entidadestado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formproject',
            name='isBlocked_project',
            field=models.BooleanField(default=True),
        ),
    ]
