# Generated by Django 5.0.6 on 2024-08-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0014_formproject_isblocked_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formproject',
            name='apellido_materno',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formproject',
            name='apellido_paterno',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formproject',
            name='area_adscripcion',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formproject',
            name='correo_institucional',
            field=models.EmailField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formproject',
            name='correo_personal',
            field=models.EmailField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formproject',
            name='nombre_dependencia',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formproject',
            name='nombre_registrante',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formproject',
            name='telefono_oficina',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='formproject',
            name='telefono_particular',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
