# Generated by Django 5.0.6 on 2024-09-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0015_alter_formproject_apellido_materno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CedulaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actual', models.DateField(auto_now_add=True)),
                ('ejercicio_fiscal', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=4)),
                ('dependencia', models.CharField(max_length=255)),
                ('organismo', models.CharField(max_length=255)),
                ('unidad_responsable', models.CharField(max_length=255)),
                ('unidad_presupuestal', models.CharField(max_length=255)),
                ('nombre_proyecto', models.CharField(max_length=250)),
                ('descripcion_proyecto', models.TextField(max_length=1000)),
                ('inversion_presupuestada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('acuerdo_aplicable', models.CharField(max_length=255)),
                ('objetivo', models.CharField(max_length=255)),
                ('prioridad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=10)),
                ('propuesta_campaña', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False)),
                ('expediente_tecnico', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False)),
            ],
        ),
    ]
