# Generated by Django 5.0.6 on 2024-09-01 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0016_cedularegistro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CedulaRegistro',
        ),
    ]
