# Generated by Django 5.0.6 on 2024-09-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0018_cedularegistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cedularegistro',
            name='isBlocked_project',
            field=models.BooleanField(default=True),
        ),
    ]
