# Generated by Django 5.0.6 on 2024-09-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0019_cedularegistro_isblocked_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cedularegistro',
            name='acuerdo_aplicable',
        ),
        migrations.RemoveField(
            model_name='cedularegistro',
            name='objetivo',
        ),
        migrations.RemoveField(
            model_name='cedularegistro',
            name='propuesta_campaña',
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='analisis_alternativas',
            field=models.FileField(blank=True, null=True, upload_to='anteProInv/analisis/alternativas/'),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='analisis_costo_beneficio',
            field=models.FileField(blank=True, null=True, upload_to='anteProInv/analisis/costo_beneficio/'),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='area_adscripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='barrio_colonia_ejido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='beneficio_economico',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='beneficio_social',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='calendario_ejecucion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='cobertura',
            field=models.CharField(blank=True, choices=[('Federal', 'Federal'), ('Regional', 'Regional'), ('Municipal', 'Municipal')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='cual_propuesta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='estrategia_ped',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='estudios_factibilidad',
            field=models.FileField(blank=True, null=True, upload_to='anteProInv/estudios/factibilidad/'),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='estudios_prospectivos',
            field=models.FileField(blank=True, null=True, upload_to='anteProInv/estudios/prospectivos/'),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='indicador_ped',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='liberacion_derecho_via',
            field=models.FileField(blank=True, null=True, upload_to='anteProInv/liberacion/derecho_via/'),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='linea_accion_ped',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='localidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='manifestacion_impacto_ambiental',
            field=models.FileField(blank=True, null=True, upload_to='anteProInv/manifestacion/impacto_ambiental/'),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='municipio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='municipios',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='nombre_dependencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='nombre_registrante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='numero_beneficiarios',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='objetivo_ped',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='ods',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='otros_estudios',
            field=models.FileField(blank=True, null=True, upload_to='anteProInv/otros/estudios/'),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='plan_estatal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='propuesta_campana',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='proyecto_ejecutivo',
            field=models.FileField(blank=True, null=True, upload_to='anteProInv/proyecto/ejecutivo/'),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='regiones',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='situacion_actual',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='situacion_con_proyecto_proyeccion',
            field=models.FileField(blank=True, null=True, upload_to='anteProInv/situacion/con_proyecto/proyeccion/'),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='situacion_sin_proyecto_fotografico',
            field=models.FileField(blank=True, null=True, upload_to='anteProInv/situacion/sin_proyecto/fotografico/'),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='tipo_obra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='validacion_normativa',
            field=models.FileField(blank=True, null=True, upload_to='anteProInv/validacion/normativa/'),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='dependencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='descripcion_proyecto',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='ejercicio_fiscal',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='expediente_tecnico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='fecha_actual',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='inversion_presupuestada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='nombre_proyecto',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='organismo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='prioridad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='unidad_presupuestal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='unidad_responsable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
