# Generated by Django 5.0.6 on 2024-09-04 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0020_remove_cedularegistro_acuerdo_aplicable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cedularegistro',
            name='barrio_colonia_ejido',
        ),
        migrations.RemoveField(
            model_name='cedularegistro',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='cedularegistro',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='cedularegistro',
            name='region',
        ),
    ]
