# Generated by Django 5.0.6 on 2024-09-04 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0021_remove_cedularegistro_barrio_colonia_ejido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cedularegistro',
            old_name='fecha_actual',
            new_name='fecha_registro',
        ),
    ]
