# Generated by Django 5.0.6 on 2024-09-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0022_rename_fecha_actual_cedularegistro_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cedularegistro',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, default='2024-01-01'),
            preserve_default=False,
        ),
    ]
