# Generated by Django 5.0.6 on 2024-09-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0023_alter_cedularegistro_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cedularegistro',
            name='cobertura',
            field=models.CharField(blank=True, choices=[('Estatal', 'Estatal'), ('Regional', 'Regional'), ('Municipal', 'Municipal')], max_length=50, null=True),
        ),
    ]
