# Generated by Django 5.0.6 on 2024-09-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0026_remove_cedularegistro_estudios_prospectivos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cedularegistro',
            old_name='expediente_Tecnico_Docu',
            new_name='expediente_tecnico_docu',
        ),
        migrations.RenameField(
            model_name='cedularegistro',
            old_name='Fotografia_Proyecto',
            new_name='fotografia_render_proyecto',
        ),
        migrations.RenameField(
            model_name='cedularegistro',
            old_name='isBlocked_project',
            new_name='is_blocked_project',
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='objetivo_programa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='programa_sectorial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True),
        ),
    ]
