# Generated by Django 5.0.6 on 2024-09-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0028_cedularegistro_projinvestment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cedularegistro',
            name='prioridad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
