# Generated by Django 5.0.6 on 2024-09-09 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0029_cedularegistro_prioridad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cedularegistro',
            name='analisis_alternativas',
        ),
        migrations.RemoveField(
            model_name='cedularegistro',
            name='analisis_costo_beneficio',
        ),
        migrations.RemoveField(
            model_name='cedularegistro',
            name='estudios_factibilidad',
        ),
        migrations.RemoveField(
            model_name='cedularegistro',
            name='expediente_tecnico_docu',
        ),
        migrations.RemoveField(
            model_name='cedularegistro',
            name='fotografia_render_proyecto',
        ),
        migrations.RemoveField(
            model_name='cedularegistro',
            name='liberacion_derecho_via',
        ),
        migrations.RemoveField(
            model_name='cedularegistro',
            name='manifestacion_impacto_ambiental',
        ),
        migrations.RemoveField(
            model_name='cedularegistro',
            name='otros_estudios',
        ),
        migrations.RemoveField(
            model_name='cedularegistro',
            name='proyecto_ejecutivo',
        ),
        migrations.RemoveField(
            model_name='cedularegistro',
            name='validacion_normativa',
        ),
        migrations.CreateModel(
            name='AnexoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_anexo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='formsDocuments/anexos/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_proyectos', to='banco_pro.cedularegistro')),
            ],
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='anexos',
            field=models.ManyToManyField(blank=True, related_name='cedulas', to='banco_pro.anexoproyecto'),
        ),
    ]
