# Generated by Django 5.0.6 on 2024-09-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0030_remove_cedularegistro_analisis_alternativas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cedularegistro',
            name='analisis_alternativas',
            field=models.FileField(blank=True, null=True, upload_to='formsDocuments/anteProInv/analisis/alternativas/'),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='analisis_costo_beneficio',
            field=models.FileField(blank=True, null=True, upload_to='formsDocuments/anteProInv/analisis/costo_beneficio/'),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='estudios_factibilidad',
            field=models.FileField(blank=True, null=True, upload_to='formsDocuments/anteProInv/estudios/factibilidad/'),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='expediente_tecnico_docu',
            field=models.FileField(blank=True, null=True, upload_to='formsDocuments/anteProInv/expediente/tecnico/'),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='fotografia_render_proyecto',
            field=models.FileField(blank=True, null=True, upload_to='formsDocuments/anteProInv/fotos/'),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='liberacion_derecho_via',
            field=models.FileField(blank=True, null=True, upload_to='formsDocuments/anteProInv/liberacion/derecho_via/'),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='manifestacion_impacto_ambiental',
            field=models.FileField(blank=True, null=True, upload_to='formsDocuments/anteProInv/manifestacion/impacto_ambiental/'),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='otros_estudios',
            field=models.FileField(blank=True, null=True, upload_to='formsDocuments/anteProInv/otros/estudios/'),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='proyecto_ejecutivo',
            field=models.FileField(blank=True, null=True, upload_to='formsDocuments/anteProInv/proyecto/ejecutivo/'),
        ),
        migrations.AddField(
            model_name='cedularegistro',
            name='validacion_normativa',
            field=models.FileField(blank=True, null=True, upload_to='formsDocuments/anteProInv/validacion/normativa/'),
        ),
    ]
