# Generated by Django 5.0.6 on 2024-09-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0031_cedularegistro_analisis_alternativas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexoproyecto',
            name='nombre_anexo',
        ),
        migrations.RemoveField(
            model_name='cedularegistro',
            name='analisis_alternativas',
        ),
        migrations.RemoveField(
            model_name='cedularegistro',
            name='analisis_costo_beneficio',
        ),
        migrations.RemoveField(
            model_name='cedularegistro',
            name='estudios_factibilidad',
        ),
        migrations.RemoveField(
            model_name='cedularegistro',
            name='expediente_tecnico_docu',
        ),
        migrations.RemoveField(
            model_name='cedularegistro',
            name='fotografia_render_proyecto',
        ),
        migrations.RemoveField(
            model_name='cedularegistro',
            name='liberacion_derecho_via',
        ),
        migrations.RemoveField(
            model_name='cedularegistro',
            name='manifestacion_impacto_ambiental',
        ),
        migrations.RemoveField(
            model_name='cedularegistro',
            name='otros_estudios',
        ),
        migrations.RemoveField(
            model_name='cedularegistro',
            name='proyecto_ejecutivo',
        ),
        migrations.RemoveField(
            model_name='cedularegistro',
            name='validacion_normativa',
        ),
        migrations.AddField(
            model_name='anexoproyecto',
            name='tipo_anexo',
            field=models.CharField(choices=[('estudios_factibilidad', 'Estudios de Factibilidad'), ('analisis_alternativas', 'Análisis de Alternativas'), ('validacion_normativa', 'Validación Normativa'), ('liberacion_derecho_via', 'Liberación de Derecho de Vía'), ('analisis_costo_beneficio', 'Análisis Costo-Beneficio'), ('expediente_tecnico_docu', 'Expediente Técnico'), ('proyecto_ejecutivo', 'Proyecto Ejecutivo'), ('manifestacion_impacto_ambiental', 'Manifestación de Impacto Ambiental'), ('fotografia_render_proyecto', 'Fotografía Render del Proyecto'), ('otros_estudios', 'Otros Estudios')], default='otros_estudios', max_length=50),
            preserve_default=False,
        ),
    ]
