# Generated by Django 5.0.6 on 2024-09-09 17:56

import banco_pro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0032_remove_anexoproyecto_nombre_anexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexoproyecto',
            name='archivo',
            field=models.FileField(upload_to=banco_pro.models.custom_upload_to),
        ),
        migrations.AlterField(
            model_name='anexoproyecto',
            name='tipo_anexo',
            field=models.CharField(choices=[('estudios_factibilidad', 'Estudios de Factibilidad'), ('analisis_alternativas', 'Análisis de Alternativas'), ('validacion_normativa', 'Validación Normativa'), ('liberacion_derecho_via', 'Liberación de Derecho de Vía'), ('analisis_costo_beneficio', 'Análisis Costo-Beneficio'), ('expediente_tecnico_docu', 'Expediente Técnico'), ('proyecto_ejecutivo', 'Proyecto Ejecutivo'), ('manifestacion_impacto_ambiental', 'Manifestación de Impacto Ambiental'), ('fotografia_render_proyecto', 'Fotografía Render del Proyecto'), ('otros_estudios', 'Otros Estudios')], default='otros_estudios', max_length=50),
        ),
    ]
