# Generated by Django 5.0.6 on 2024-09-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0034_cedularegistro_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cedularegistro',
            name='cual_propuesta',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='estrategia_ped',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='indicador_ped',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='linea_accion_ped',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='objetivo_ped',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='objetivo_programa',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='ods',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='plan_estatal',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='prioridad',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='programa_sectorial',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
