# Generated by Django 5.0.6 on 2024-09-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0036_alter_cedularegistro_cual_propuesta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cedularegistro',
            name='estrategia_ped',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='indicador_ped',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='linea_accion_ped',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='objetivo_ped',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='objetivo_programa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='programa_sectorial',
            field=models.TextField(blank=True, null=True),
        ),
    ]
