# Generated by Django 5.0.6 on 2024-09-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0038_alter_cedularegistro_estrategia_ped_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cedularegistro',
            name='cual_propuesta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='estrategia_ped',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='indicador_ped',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='objetivo_ped',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='objetivo_programa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='ods',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='plan_estatal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='prioridad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cedularegistro',
            name='programa_sectorial',
            field=models.TextField(blank=True, null=True),
        ),
    ]
