# Generated by Django 5.0.6 on 2024-11-26 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0039_alter_cedularegistro_cual_propuesta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formproject',
            name='nombre_dependencia',
        ),
    ]
