# Generated by Django 5.0.6 on 2024-11-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0040_remove_formproject_nombre_dependencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formproject',
            old_name='correo_institucional',
            new_name='correo',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='correo_personal',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='telefono_particular',
        ),
    ]
