# Generated by Django 5.0.6 on 2024-11-26 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0041_rename_correo_institucional_formproject_correo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formproject',
            old_name='isBlocked_project_name',
            new_name='isBlocked_nombre_proyecto',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='municipioEnd',
            new_name='municipio_ayuntamiento',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='project_name',
            new_name='nombre_proyecto',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='observacion_project_name',
            new_name='observacion_nombre_proyecto',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='telefono_oficina',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='telefono_oficina_ext',
            new_name='telefono_ext',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='peticion_personal',
        ),
    ]
