# Generated by Django 5.0.6 on 2024-11-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0042_rename_isblocked_project_name_formproject_isblocked_nombre_proyecto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formproject',
            old_name='barrio_colonia_ejido',
            new_name='barrio_colonia',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='alineacion_normativa',
            new_name='normativa_aplicable',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='entidadEstado',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='indicadores_desempeno',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='indicadores_rentabilidad',
        ),
        migrations.AddField(
            model_name='formproject',
            name='acuerdos_transversales',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
