# Generated by Django 5.0.6 on 2024-11-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0043_rename_barrio_colonia_ejido_formproject_barrio_colonia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formproject',
            old_name='isBlocked_barrio_colonia_ejido',
            new_name='isBlocked_barrio_colonia',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='isBlocked_municipioEnd',
            new_name='isBlocked_municipio_ayuntamiento',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='isBlocked_alineacion_normativa',
            new_name='isBlocked_normativa_aplicable',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='observacion_barrio_colonia_ejido',
            new_name='observacion_barrio_colonia',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='observacion_entidadEstado',
            new_name='observacion_municipio_ayuntamiento',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='observacion_alineacion_normativa',
            new_name='observacion_normativa_aplicable',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='estado_con_proyecto',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='isBlocked_entidadEstado',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='isBlocked_estado_con_proyecto',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='isBlocked_indicadores_desempeno',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='isBlocked_indicadores_rentabilidad',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='isBlocked_peticion_personal',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='observacion_estado_con_proyecto',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='observacion_indicadores_desempeno',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='observacion_indicadores_rentabilidad',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='observacion_municipioEnd',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='observacion_peticion_personal',
        ),
        migrations.AddField(
            model_name='formproject',
            name='isBlocked_acuerdos_transversales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_acuerdos_transversales',
            field=models.TextField(blank=True, null=True),
        ),
    ]
