# Generated by Django 5.0.6 on 2024-11-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0044_rename_isblocked_barrio_colonia_ejido_formproject_isblocked_barrio_colonia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formproject',
            old_name='isBlocked_estado_inicial',
            new_name='isBlocked_situacion_actual',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='observacion_estado_inicial',
            new_name='observacion_situacion_actual',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='estado_inicial',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='estudios_prospectivos',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='isBlocked_estudios_prospectivos',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='isBlocked_situacion_con_proyecto_proyeccion',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='isBlocked_situacion_sin_proyecto_fotografico',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='observacion_estudios_prospectivos',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='observacion_situacion_con_proyecto_proyeccion',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='observacion_situacion_sin_proyecto_fotografico',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='situacion_con_proyecto_proyeccion',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='situacion_sin_proyecto_fotografico',
        ),
        migrations.AddField(
            model_name='formproject',
            name='isBlocked_render',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_render',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='render',
            field=models.FileField(blank=True, null=True, upload_to='documentos/render/'),
        ),
        migrations.AddField(
            model_name='formproject',
            name='situacion_actual',
            field=models.ImageField(blank=True, null=True, upload_to='documentos/situacion_actual/'),
        ),
    ]
