# Generated by Django 5.0.6 on 2024-11-26 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0046_rename_inversion_estimada_formproject_inversion_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formproject',
            old_name='monto_estatal',
            new_name='inversion_estatal',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='monto_federal',
            new_name='inversion_federal',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='monto_municipal',
            new_name='inversion_municipal',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='monto_otros',
            new_name='inversion_otros',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='isBlocked_monto_estatal',
            new_name='isBlocked_inversion_estatal',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='isBlocked_monto_federal',
            new_name='isBlocked_inversion_federal',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='isBlocked_monto_municipal',
            new_name='isBlocked_inversion_municipal',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='isBlocked_monto_otros',
            new_name='isBlocked_inversion_otros',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='observacion_monto_estatal',
            new_name='observacion_inversion_estatal',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='observacion_monto_federal',
            new_name='observacion_inversion_federal',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='observacion_monto_municipal',
            new_name='observacion_inversion_municipal',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='observacion_monto_otros',
            new_name='observacion_inversion_otros',
        ),
    ]
