# Generated by Django 5.0.6 on 2024-11-26 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0047_rename_monto_estatal_formproject_inversion_estatal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formproject',
            old_name='isBlocked_plan_sectorial',
            new_name='isBlocked_programas_SIE',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='observacion_plan_sectorial',
            new_name='observacion_programas_SIE',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='plan_sectorial',
            new_name='programas_SIE',
        ),
    ]
