# Generated by Django 5.0.6 on 2025-01-31 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0048_rename_isblocked_plan_sectorial_formproject_isblocked_programas_sie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formproject',
            name='gasto_programable',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='indicadores_tacticos',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='isBlocked_gasto_programable',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='isBlocked_indicadores_tacticos',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='observacion_gasto_programable',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='observacion_indicadores_tacticos',
        ),
        migrations.AddField(
            model_name='formproject',
            name='isBlocked_modalidadEjecucion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formproject',
            name='isBlocked_tiemposEjecucion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formproject',
            name='modalidadEjecucion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_modalidadEjecucion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_tiemposEjecucion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formproject',
            name='tiemposEjecucion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
