# Generated by Django 5.0.6 on 2025-01-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0049_remove_formproject_gasto_programable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formproject',
            name='gasto_programable',
            field=models.CharField(default='Prueba', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formproject',
            name='isBlocked_gasto_programable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_gasto_programable',
            field=models.TextField(blank=True, null=True),
        ),
    ]
