# Generated by Django 5.0.6 on 2025-01-31 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0050_formproject_gasto_programable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formproject',
            old_name='modalidadEjecucion',
            new_name='modalidad_ejecucion',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='tiemposEjecucion',
            new_name='tiempos_ejecucion',
        ),
    ]
