# Generated by Django 5.0.6 on 2025-01-31 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0051_rename_modalidadejecucion_formproject_modalidad_ejecucion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formproject',
            old_name='isBlocked_modalidadEjecucion',
            new_name='isBlocked_modalidad_ejecucion',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='isBlocked_tiemposEjecucion',
            new_name='isBlocked_tiempos_ejecucion',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='observacion_modalidadEjecucion',
            new_name='observacion_modalidad_ejecucion',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='observacion_tiemposEjecucion',
            new_name='observacion_tiempos_ejecucion',
        ),
    ]
