# Generated by Django 5.0.6 on 2025-01-31 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0052_rename_isblocked_modalidadejecucion_formproject_isblocked_modalidad_ejecucion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formproject',
            old_name='isBlocked_tiempos_ejecucion',
            new_name='isBlocked_tiempo_ejecucion',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='observacion_tiempos_ejecucion',
            new_name='observacion_tiempo_ejecucion',
        ),
        migrations.RenameField(
            model_name='formproject',
            old_name='tiempos_ejecucion',
            new_name='tiempo_ejecucion',
        ),
    ]
