# Generated by Django 5.0.6 on 2025-01-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0053_rename_isblocked_tiempos_ejecucion_formproject_isblocked_tiempo_ejecucion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formproject',
            name='modalidad_ejecucion',
            field=models.CharField(default='prueba', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formproject',
            name='observacion_modalidad_ejecucion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
