# Generated by Django 5.0.6 on 2025-02-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0054_alter_formproject_modalidad_ejecucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formproject',
            name='indicadores_socioeconomicos',
            field=models.CharField(default='por definir', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formproject',
            name='isBlocked_indicadores_socioeconomicos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formproject',
            name='isBlocked_tipo_localidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_indicadores_socioeconomicos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='observacion_tipo_localidad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formproject',
            name='tipo_localidad',
            field=models.CharField(default='por definir', max_length=255),
            preserve_default=False,
        ),
    ]
