# Generated by Django 5.0.6 on 2025-02-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0055_formproject_indicadores_socioeconomicos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formproject',
            name='municipio',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='formproject',
            name='region',
            field=models.JSONField(),
        ),
    ]
