# Generated by Django 5.0.6 on 2025-02-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0057_alter_formproject_municipio_alter_formproject_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formproject',
            name='municipio',
            field=models.JSONField(default='prueba'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formproject',
            name='region',
            field=models.JSONField(default='prueba'),
            preserve_default=False,
        ),
    ]
