# Generated by Django 5.0.6 on 2025-02-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco_pro', '0058_alter_formproject_municipio_alter_formproject_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formproject',
            name='isBlocked_municipio_impacto',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='municipio_impacto',
        ),
        migrations.RemoveField(
            model_name='formproject',
            name='observacion_municipio_impacto',
        ),
    ]
